# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\SC_spectrum\SC_gas_set.ui'
#
# Created: Wed Jan 20 21:59:41 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SC_gas(object):
    def setupUi(self, SC_gas):
        SC_gas.setObjectName(_fromUtf8("SC_gas"))
        SC_gas.resize(640, 480)
        SC_gas.setMinimumSize(QtCore.QSize(640, 480))
        SC_gas.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        SC_gas.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/gastitle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SC_gas.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SC_gas)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setContentsMargins(10, 10, 10, 30)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_34 = QtGui.QLabel(SC_gas)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_2.addWidget(self.label_34)
        self.work_mode = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_mode.sizePolicy().hasHeightForWidth())
        self.work_mode.setSizePolicy(sizePolicy)
        self.work_mode.setObjectName(_fromUtf8("work_mode"))
        self.work_mode.addItem(_fromUtf8(""))
        self.work_mode.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.work_mode)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setMargin(10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label = QtGui.QLabel(SC_gas)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_25.addWidget(self.label)
        self.total_flow = QtGui.QLineEdit(SC_gas)
        self.total_flow.setEnabled(True)
        self.total_flow.setMaximumSize(QtCore.QSize(80, 22))
        self.total_flow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.total_flow.setText(_fromUtf8(""))
        self.total_flow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_flow.setObjectName(_fromUtf8("total_flow"))
        self.horizontalLayout_25.addWidget(self.total_flow)
        self.flow_unit = QtGui.QLabel(SC_gas)
        self.flow_unit.setObjectName(_fromUtf8("flow_unit"))
        self.horizontalLayout_25.addWidget(self.flow_unit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(10)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem2)
        self.label_30 = QtGui.QLabel(SC_gas)
        self.label_30.setMinimumSize(QtCore.QSize(40, 22))
        self.label_30.setMaximumSize(QtCore.QSize(40, 22))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_26.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(SC_gas)
        self.label_31.setMinimumSize(QtCore.QSize(106, 22))
        self.label_31.setMaximumSize(QtCore.QSize(106, 22))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_26.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(SC_gas)
        self.label_32.setMinimumSize(QtCore.QSize(100, 22))
        self.label_32.setMaximumSize(QtCore.QSize(100, 22))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_26.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(SC_gas)
        self.label_33.setMinimumSize(QtCore.QSize(120, 22))
        self.label_33.setMaximumSize(QtCore.QSize(120, 22))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_26.addWidget(self.label_33)
        self.label_38 = QtGui.QLabel(SC_gas)
        self.label_38.setMinimumSize(QtCore.QSize(80, 22))
        self.label_38.setMaximumSize(QtCore.QSize(80, 22))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_26.addWidget(self.label_38)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(10)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.flow1 = QtGui.QCheckBox(SC_gas)
        self.flow1.setMinimumSize(QtCore.QSize(80, 20))
        self.flow1.setMaximumSize(QtCore.QSize(80, 20))
        self.flow1.setObjectName(_fromUtf8("flow1"))
        self.horizontalLayout_28.addWidget(self.flow1)
        self.flow1_range = QtGui.QLineEdit(SC_gas)
        self.flow1_range.setEnabled(False)
        self.flow1_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow1_range.setObjectName(_fromUtf8("flow1_range"))
        self.horizontalLayout_28.addWidget(self.flow1_range)
        self.flow1_type = QtGui.QComboBox(SC_gas)
        self.flow1_type.setMinimumSize(QtCore.QSize(106, 21))
        self.flow1_type.setMaximumSize(QtCore.QSize(106, 21))
        self.flow1_type.setObjectName(_fromUtf8("flow1_type"))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.flow1_type.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.flow1_type)
        self.flow1_change = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow1_change.sizePolicy().hasHeightForWidth())
        self.flow1_change.setSizePolicy(sizePolicy)
        self.flow1_change.setMinimumSize(QtCore.QSize(100, 22))
        self.flow1_change.setMaximumSize(QtCore.QSize(100, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow1_change.setFont(font)
        self.flow1_change.setObjectName(_fromUtf8("flow1_change"))
        self.flow1_change.addItem(_fromUtf8(""))
        self.flow1_change.addItem(_fromUtf8(""))
        self.flow1_change.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.flow1_change)
        self.flow1_value = QtGui.QLineEdit(SC_gas)
        self.flow1_value.setMinimumSize(QtCore.QSize(120, 22))
        self.flow1_value.setMaximumSize(QtCore.QSize(120, 22))
        self.flow1_value.setObjectName(_fromUtf8("flow1_value"))
        self.horizontalLayout_28.addWidget(self.flow1_value)
        self.flow1_unit = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow1_unit.sizePolicy().hasHeightForWidth())
        self.flow1_unit.setSizePolicy(sizePolicy)
        self.flow1_unit.setMinimumSize(QtCore.QSize(80, 22))
        self.flow1_unit.setMaximumSize(QtCore.QSize(80, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow1_unit.setFont(font)
        self.flow1_unit.setObjectName(_fromUtf8("flow1_unit"))
        self.flow1_unit.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.flow1_unit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.flow2 = QtGui.QCheckBox(SC_gas)
        self.flow2.setMinimumSize(QtCore.QSize(80, 20))
        self.flow2.setMaximumSize(QtCore.QSize(80, 20))
        self.flow2.setObjectName(_fromUtf8("flow2"))
        self.horizontalLayout_29.addWidget(self.flow2)
        self.flow2_range = QtGui.QLineEdit(SC_gas)
        self.flow2_range.setEnabled(False)
        self.flow2_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow2_range.setObjectName(_fromUtf8("flow2_range"))
        self.horizontalLayout_29.addWidget(self.flow2_range)
        self.flow2_type = QtGui.QComboBox(SC_gas)
        self.flow2_type.setMinimumSize(QtCore.QSize(106, 21))
        self.flow2_type.setMaximumSize(QtCore.QSize(106, 21))
        self.flow2_type.setObjectName(_fromUtf8("flow2_type"))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.flow2_type.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.flow2_type)
        self.flow2_change = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow2_change.sizePolicy().hasHeightForWidth())
        self.flow2_change.setSizePolicy(sizePolicy)
        self.flow2_change.setMinimumSize(QtCore.QSize(100, 22))
        self.flow2_change.setMaximumSize(QtCore.QSize(100, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow2_change.setFont(font)
        self.flow2_change.setObjectName(_fromUtf8("flow2_change"))
        self.flow2_change.addItem(_fromUtf8(""))
        self.flow2_change.addItem(_fromUtf8(""))
        self.flow2_change.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.flow2_change)
        self.flow2_value = QtGui.QLineEdit(SC_gas)
        self.flow2_value.setMinimumSize(QtCore.QSize(120, 22))
        self.flow2_value.setMaximumSize(QtCore.QSize(120, 22))
        self.flow2_value.setObjectName(_fromUtf8("flow2_value"))
        self.horizontalLayout_29.addWidget(self.flow2_value)
        self.flow2_unit = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow2_unit.sizePolicy().hasHeightForWidth())
        self.flow2_unit.setSizePolicy(sizePolicy)
        self.flow2_unit.setMinimumSize(QtCore.QSize(80, 22))
        self.flow2_unit.setMaximumSize(QtCore.QSize(80, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow2_unit.setFont(font)
        self.flow2_unit.setObjectName(_fromUtf8("flow2_unit"))
        self.flow2_unit.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.flow2_unit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(10)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.flow3 = QtGui.QCheckBox(SC_gas)
        self.flow3.setMinimumSize(QtCore.QSize(80, 20))
        self.flow3.setMaximumSize(QtCore.QSize(80, 20))
        self.flow3.setObjectName(_fromUtf8("flow3"))
        self.horizontalLayout_30.addWidget(self.flow3)
        self.flow3_range = QtGui.QLineEdit(SC_gas)
        self.flow3_range.setEnabled(False)
        self.flow3_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow3_range.setObjectName(_fromUtf8("flow3_range"))
        self.horizontalLayout_30.addWidget(self.flow3_range)
        self.flow3_type = QtGui.QComboBox(SC_gas)
        self.flow3_type.setMinimumSize(QtCore.QSize(106, 21))
        self.flow3_type.setMaximumSize(QtCore.QSize(106, 21))
        self.flow3_type.setObjectName(_fromUtf8("flow3_type"))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.flow3_type.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.flow3_type)
        self.flow3_change = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow3_change.sizePolicy().hasHeightForWidth())
        self.flow3_change.setSizePolicy(sizePolicy)
        self.flow3_change.setMinimumSize(QtCore.QSize(100, 22))
        self.flow3_change.setMaximumSize(QtCore.QSize(100, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow3_change.setFont(font)
        self.flow3_change.setObjectName(_fromUtf8("flow3_change"))
        self.flow3_change.addItem(_fromUtf8(""))
        self.flow3_change.addItem(_fromUtf8(""))
        self.flow3_change.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.flow3_change)
        self.flow3_value = QtGui.QLineEdit(SC_gas)
        self.flow3_value.setMinimumSize(QtCore.QSize(120, 22))
        self.flow3_value.setMaximumSize(QtCore.QSize(120, 22))
        self.flow3_value.setObjectName(_fromUtf8("flow3_value"))
        self.horizontalLayout_30.addWidget(self.flow3_value)
        self.flow3_unit = QtGui.QComboBox(SC_gas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flow3_unit.sizePolicy().hasHeightForWidth())
        self.flow3_unit.setSizePolicy(sizePolicy)
        self.flow3_unit.setMinimumSize(QtCore.QSize(80, 22))
        self.flow3_unit.setMaximumSize(QtCore.QSize(80, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flow3_unit.setFont(font)
        self.flow3_unit.setObjectName(_fromUtf8("flow3_unit"))
        self.flow3_unit.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.flow3_unit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setSpacing(6)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_41 = QtGui.QLabel(SC_gas)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_36.addWidget(self.label_41)
        self.res_offset = QtGui.QLineEdit(SC_gas)
        self.res_offset.setMaximumSize(QtCore.QSize(124, 22))
        self.res_offset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.res_offset.setText(_fromUtf8(""))
        self.res_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_offset.setObjectName(_fromUtf8("res_offset"))
        self.horizontalLayout_36.addWidget(self.res_offset)
        self.flow_unit_4 = QtGui.QLabel(SC_gas)
        self.flow_unit_4.setObjectName(_fromUtf8("flow_unit_4"))
        self.horizontalLayout_36.addWidget(self.flow_unit_4)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_36)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setSpacing(6)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_42 = QtGui.QLabel(SC_gas)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_37.addWidget(self.label_42)
        self.res_stable = QtGui.QLineEdit(SC_gas)
        self.res_stable.setMaximumSize(QtCore.QSize(124, 22))
        self.res_stable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.res_stable.setText(_fromUtf8(""))
        self.res_stable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_stable.setObjectName(_fromUtf8("res_stable"))
        self.horizontalLayout_37.addWidget(self.res_stable)
        self.flow_unit_5 = QtGui.QLabel(SC_gas)
        self.flow_unit_5.setObjectName(_fromUtf8("flow_unit_5"))
        self.horizontalLayout_37.addWidget(self.flow_unit_5)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_37)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setSpacing(6)
        self.horizontalLayout_39.setContentsMargins(32, -1, -1, -1)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_43 = QtGui.QLabel(SC_gas)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_39.addWidget(self.label_43)
        self.response_time = QtGui.QLineEdit(SC_gas)
        self.response_time.setMaximumSize(QtCore.QSize(124, 22))
        self.response_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.response_time.setText(_fromUtf8(""))
        self.response_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.response_time.setObjectName(_fromUtf8("response_time"))
        self.horizontalLayout_39.addWidget(self.response_time)
        self.flow_unit_6 = QtGui.QLabel(SC_gas)
        self.flow_unit_6.setObjectName(_fromUtf8("flow_unit_6"))
        self.horizontalLayout_39.addWidget(self.flow_unit_6)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_39)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem4)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(6)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_44 = QtGui.QLabel(SC_gas)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_40.addWidget(self.label_44)
        self.recovery_time = QtGui.QLineEdit(SC_gas)
        self.recovery_time.setMaximumSize(QtCore.QSize(124, 22))
        self.recovery_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recovery_time.setText(_fromUtf8(""))
        self.recovery_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recovery_time.setObjectName(_fromUtf8("recovery_time"))
        self.horizontalLayout_40.addWidget(self.recovery_time)
        self.flow_unit_7 = QtGui.QLabel(SC_gas)
        self.flow_unit_7.setObjectName(_fromUtf8("flow_unit_7"))
        self.horizontalLayout_40.addWidget(self.flow_unit_7)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_40)
        self.verticalLayout_7.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_2 = QtGui.QLabel(SC_gas)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_31.addWidget(self.label_2)
        self.repeat = QtGui.QLineEdit(SC_gas)
        self.repeat.setEnabled(True)
        self.repeat.setMaximumSize(QtCore.QSize(155, 22))
        self.repeat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.repeat.setText(_fromUtf8(""))
        self.repeat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.repeat.setObjectName(_fromUtf8("repeat"))
        self.horizontalLayout_31.addWidget(self.repeat)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(10)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem7)
        self.SC_gas_save = QtGui.QPushButton(SC_gas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SC_gas_save.setFont(font)
        self.SC_gas_save.setObjectName(_fromUtf8("SC_gas_save"))
        self.horizontalLayout_27.addWidget(self.SC_gas_save)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.SC_gas_exit = QtGui.QPushButton(SC_gas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SC_gas_exit.setFont(font)
        self.SC_gas_exit.setObjectName(_fromUtf8("SC_gas_exit"))
        self.horizontalLayout_27.addWidget(self.SC_gas_exit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SC_gas)
        QtCore.QObject.connect(self.SC_gas_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), SC_gas.close)
        QtCore.QMetaObject.connectSlotsByName(SC_gas)

    def retranslateUi(self, SC_gas):
        SC_gas.setWindowTitle(_translate("SC_gas", "S-C谱气压控制", None))
        self.label_34.setText(_translate("SC_gas", "工作模式", None))
        self.work_mode.setItemText(0, _translate("SC_gas", "自动", None))
        self.work_mode.setItemText(1, _translate("SC_gas", "手动", None))
        self.label.setText(_translate("SC_gas", "总流量", None))
        self.flow_unit.setText(_translate("SC_gas", "mL", None))
        self.label_30.setText(_translate("SC_gas", "量程", None))
        self.label_31.setText(_translate("SC_gas", "气体类型", None))
        self.label_32.setText(_translate("SC_gas", "变化方式", None))
        self.label_33.setText(_translate("SC_gas", "流量", None))
        self.label_38.setText(_translate("SC_gas", "单位", None))
        self.flow1.setText(_translate("SC_gas", "流量计1", None))
        self.flow1_range.setText(_translate("SC_gas", "2000", None))
        self.flow1_type.setItemText(0, _translate("SC_gas", "空气", None))
        self.flow1_type.setItemText(1, _translate("SC_gas", "氩气", None))
        self.flow1_type.setItemText(2, _translate("SC_gas", "四氟化碳", None))
        self.flow1_type.setItemText(3, _translate("SC_gas", "甲烷", None))
        self.flow1_type.setItemText(4, _translate("SC_gas", "三氟甲烷", None))
        self.flow1_type.setItemText(5, _translate("SC_gas", "乙烯", None))
        self.flow1_type.setItemText(6, _translate("SC_gas", "乙烷", None))
        self.flow1_type.setItemText(7, _translate("SC_gas", "六氟乙烷", None))
        self.flow1_type.setItemText(8, _translate("SC_gas", "丙烯", None))
        self.flow1_type.setItemText(9, _translate("SC_gas", "丙烷", None))
        self.flow1_type.setItemText(10, _translate("SC_gas", "异丁烯", None))
        self.flow1_type.setItemText(11, _translate("SC_gas", "正丁烷", None))
        self.flow1_type.setItemText(12, _translate("SC_gas", "异丁烷", None))
        self.flow1_type.setItemText(13, _translate("SC_gas", "一氧化碳", None))
        self.flow1_type.setItemText(14, _translate("SC_gas", "二氧化碳", None))
        self.flow1_type.setItemText(15, _translate("SC_gas", "氯气", None))
        self.flow1_type.setItemText(16, _translate("SC_gas", "氢气", None))
        self.flow1_type.setItemText(17, _translate("SC_gas", "氯化氢", None))
        self.flow1_type.setItemText(18, _translate("SC_gas", "氦气", None))
        self.flow1_type.setItemText(19, _translate("SC_gas", "氪气", None))
        self.flow1_type.setItemText(20, _translate("SC_gas", "氮气", None))
        self.flow1_type.setItemText(21, _translate("SC_gas", "三氟化氮", None))
        self.flow1_type.setItemText(22, _translate("SC_gas", "一氧化氮", None))
        self.flow1_type.setItemText(23, _translate("SC_gas", "一氧化二氮", None))
        self.flow1_type.setItemText(24, _translate("SC_gas", "氖气", None))
        self.flow1_type.setItemText(25, _translate("SC_gas", "氧气", None))
        self.flow1_type.setItemText(26, _translate("SC_gas", "硅烷", None))
        self.flow1_type.setItemText(27, _translate("SC_gas", "六氟化硫", None))
        self.flow1_type.setItemText(28, _translate("SC_gas", "二氧化硫", None))
        self.flow1_type.setItemText(29, _translate("SC_gas", "氙气", None))
        self.flow1_change.setItemText(0, _translate("SC_gas", "恒定", None))
        self.flow1_change.setItemText(1, _translate("SC_gas", "10% - 90%", None))
        self.flow1_change.setItemText(2, _translate("SC_gas", "90% - 10%", None))
        self.flow1_unit.setItemText(0, _translate("SC_gas", "mL/min", None))
        self.flow2.setText(_translate("SC_gas", "流量计2", None))
        self.flow2_range.setText(_translate("SC_gas", "500", None))
        self.flow2_type.setItemText(0, _translate("SC_gas", "空气", None))
        self.flow2_type.setItemText(1, _translate("SC_gas", "氩气", None))
        self.flow2_type.setItemText(2, _translate("SC_gas", "四氟化碳", None))
        self.flow2_type.setItemText(3, _translate("SC_gas", "甲烷", None))
        self.flow2_type.setItemText(4, _translate("SC_gas", "三氟甲烷", None))
        self.flow2_type.setItemText(5, _translate("SC_gas", "乙烯", None))
        self.flow2_type.setItemText(6, _translate("SC_gas", "乙烷", None))
        self.flow2_type.setItemText(7, _translate("SC_gas", "六氟乙烷", None))
        self.flow2_type.setItemText(8, _translate("SC_gas", "丙烯", None))
        self.flow2_type.setItemText(9, _translate("SC_gas", "丙烷", None))
        self.flow2_type.setItemText(10, _translate("SC_gas", "异丁烯", None))
        self.flow2_type.setItemText(11, _translate("SC_gas", "正丁烷", None))
        self.flow2_type.setItemText(12, _translate("SC_gas", "异丁烷", None))
        self.flow2_type.setItemText(13, _translate("SC_gas", "一氧化碳", None))
        self.flow2_type.setItemText(14, _translate("SC_gas", "二氧化碳", None))
        self.flow2_type.setItemText(15, _translate("SC_gas", "氯气", None))
        self.flow2_type.setItemText(16, _translate("SC_gas", "氢气", None))
        self.flow2_type.setItemText(17, _translate("SC_gas", "氯化氢", None))
        self.flow2_type.setItemText(18, _translate("SC_gas", "氦气", None))
        self.flow2_type.setItemText(19, _translate("SC_gas", "氪气", None))
        self.flow2_type.setItemText(20, _translate("SC_gas", "氮气", None))
        self.flow2_type.setItemText(21, _translate("SC_gas", "三氟化氮", None))
        self.flow2_type.setItemText(22, _translate("SC_gas", "一氧化氮", None))
        self.flow2_type.setItemText(23, _translate("SC_gas", "一氧化二氮", None))
        self.flow2_type.setItemText(24, _translate("SC_gas", "氖气", None))
        self.flow2_type.setItemText(25, _translate("SC_gas", "氧气", None))
        self.flow2_type.setItemText(26, _translate("SC_gas", "硅烷", None))
        self.flow2_type.setItemText(27, _translate("SC_gas", "六氟化硫", None))
        self.flow2_type.setItemText(28, _translate("SC_gas", "二氧化硫", None))
        self.flow2_type.setItemText(29, _translate("SC_gas", "氙气", None))
        self.flow2_change.setItemText(0, _translate("SC_gas", "恒定", None))
        self.flow2_change.setItemText(1, _translate("SC_gas", "10% - 90%", None))
        self.flow2_change.setItemText(2, _translate("SC_gas", "90% - 10%", None))
        self.flow2_unit.setItemText(0, _translate("SC_gas", "mL/min", None))
        self.flow3.setText(_translate("SC_gas", "流量计3", None))
        self.flow3_range.setText(_translate("SC_gas", "50", None))
        self.flow3_type.setItemText(0, _translate("SC_gas", "空气", None))
        self.flow3_type.setItemText(1, _translate("SC_gas", "氩气", None))
        self.flow3_type.setItemText(2, _translate("SC_gas", "四氟化碳", None))
        self.flow3_type.setItemText(3, _translate("SC_gas", "甲烷", None))
        self.flow3_type.setItemText(4, _translate("SC_gas", "三氟甲烷", None))
        self.flow3_type.setItemText(5, _translate("SC_gas", "乙烯", None))
        self.flow3_type.setItemText(6, _translate("SC_gas", "乙烷", None))
        self.flow3_type.setItemText(7, _translate("SC_gas", "六氟乙烷", None))
        self.flow3_type.setItemText(8, _translate("SC_gas", "丙烯", None))
        self.flow3_type.setItemText(9, _translate("SC_gas", "丙烷", None))
        self.flow3_type.setItemText(10, _translate("SC_gas", "异丁烯", None))
        self.flow3_type.setItemText(11, _translate("SC_gas", "正丁烷", None))
        self.flow3_type.setItemText(12, _translate("SC_gas", "异丁烷", None))
        self.flow3_type.setItemText(13, _translate("SC_gas", "一氧化碳", None))
        self.flow3_type.setItemText(14, _translate("SC_gas", "二氧化碳", None))
        self.flow3_type.setItemText(15, _translate("SC_gas", "氯气", None))
        self.flow3_type.setItemText(16, _translate("SC_gas", "氢气", None))
        self.flow3_type.setItemText(17, _translate("SC_gas", "氯化氢", None))
        self.flow3_type.setItemText(18, _translate("SC_gas", "氦气", None))
        self.flow3_type.setItemText(19, _translate("SC_gas", "氪气", None))
        self.flow3_type.setItemText(20, _translate("SC_gas", "氮气", None))
        self.flow3_type.setItemText(21, _translate("SC_gas", "三氟化氮", None))
        self.flow3_type.setItemText(22, _translate("SC_gas", "一氧化氮", None))
        self.flow3_type.setItemText(23, _translate("SC_gas", "一氧化二氮", None))
        self.flow3_type.setItemText(24, _translate("SC_gas", "氖气", None))
        self.flow3_type.setItemText(25, _translate("SC_gas", "氧气", None))
        self.flow3_type.setItemText(26, _translate("SC_gas", "硅烷", None))
        self.flow3_type.setItemText(27, _translate("SC_gas", "六氟化硫", None))
        self.flow3_type.setItemText(28, _translate("SC_gas", "二氧化硫", None))
        self.flow3_type.setItemText(29, _translate("SC_gas", "氙气", None))
        self.flow3_change.setItemText(0, _translate("SC_gas", "恒定", None))
        self.flow3_change.setItemText(1, _translate("SC_gas", "10% - 90%", None))
        self.flow3_change.setItemText(2, _translate("SC_gas", "90% - 10%", None))
        self.flow3_unit.setItemText(0, _translate("SC_gas", "mL/min", None))
        self.label_41.setText(_translate("SC_gas", "电阻偏差范围", None))
        self.flow_unit_4.setText(_translate("SC_gas", "Ω", None))
        self.label_42.setText(_translate("SC_gas", "电阻稳定时间", None))
        self.flow_unit_5.setText(_translate("SC_gas", "S", None))
        self.label_43.setText(_translate("SC_gas", "响应时间", None))
        self.flow_unit_6.setText(_translate("SC_gas", "S", None))
        self.label_44.setText(_translate("SC_gas", "恢复时间", None))
        self.flow_unit_7.setText(_translate("SC_gas", "S", None))
        self.label_2.setText(_translate("SC_gas", "测量次数", None))
        self.SC_gas_save.setText(_translate("SC_gas", "保存", None))
        self.SC_gas_exit.setText(_translate("SC_gas", "退出", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SC_gas = QtGui.QDialog()
    ui = Ui_SC_gas()
    ui.setupUi(SC_gas)
    SC_gas.show()
    sys.exit(app.exec_())

