# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\coordinate.ui'
#
# Created: Thu Dec 24 22:33:56 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UI_Coordinate(object):
    def setupUi(self, UI_Coordinate):
        UI_Coordinate.setObjectName(_fromUtf8("UI_Coordinate"))
        UI_Coordinate.resize(320, 240)
        UI_Coordinate.setMinimumSize(QtCore.QSize(320, 240))
        UI_Coordinate.setMaximumSize(QtCore.QSize(320, 240))
        font = QtGui.QFont()
        font.setPointSize(12)
        UI_Coordinate.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/324264.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI_Coordinate.setWindowIcon(icon)
        self.verticalLayout_6 = QtGui.QVBoxLayout(UI_Coordinate)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.auto_fit = QtGui.QCheckBox(UI_Coordinate)
        self.auto_fit.setObjectName(_fromUtf8("auto_fit"))
        self.verticalLayout_5.addWidget(self.auto_fit)
        self.groupBox = QtGui.QGroupBox(UI_Coordinate)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.x_min = QtGui.QLineEdit(self.groupBox)
        self.x_min.setMinimumSize(QtCore.QSize(0, 22))
        self.x_min.setObjectName(_fromUtf8("x_min"))
        self.horizontalLayout.addWidget(self.x_min)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.x_max = QtGui.QLineEdit(self.groupBox)
        self.x_max.setMinimumSize(QtCore.QSize(0, 22))
        self.x_max.setObjectName(_fromUtf8("x_max"))
        self.horizontalLayout_2.addWidget(self.x_max)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.y_min = QtGui.QLineEdit(self.groupBox)
        self.y_min.setMinimumSize(QtCore.QSize(0, 22))
        self.y_min.setObjectName(_fromUtf8("y_min"))
        self.horizontalLayout_4.addWidget(self.y_min)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.y_max = QtGui.QLineEdit(self.groupBox)
        self.y_max.setMinimumSize(QtCore.QSize(0, 22))
        self.y_max.setObjectName(_fromUtf8("y_max"))
        self.horizontalLayout_5.addWidget(self.y_max)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.xyset_ok = QtGui.QPushButton(UI_Coordinate)
        self.xyset_ok.setObjectName(_fromUtf8("xyset_ok"))
        self.horizontalLayout_3.addWidget(self.xyset_ok)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.xyset_cancel = QtGui.QPushButton(UI_Coordinate)
        self.xyset_cancel.setObjectName(_fromUtf8("xyset_cancel"))
        self.horizontalLayout_3.addWidget(self.xyset_cancel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(UI_Coordinate)
        QtCore.QObject.connect(self.xyset_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), UI_Coordinate.close)
        QtCore.QObject.connect(self.xyset_ok, QtCore.SIGNAL(_fromUtf8("clicked()")), UI_Coordinate.close)
        QtCore.QMetaObject.connectSlotsByName(UI_Coordinate)

    def retranslateUi(self, UI_Coordinate):
        UI_Coordinate.setWindowTitle(_translate("UI_Coordinate", "坐标设置", None))
        self.auto_fit.setText(_translate("UI_Coordinate", "自适应", None))
        self.groupBox.setTitle(_translate("UI_Coordinate", "坐标范围", None))
        self.label.setText(_translate("UI_Coordinate", "X轴", None))
        self.label_3.setText(_translate("UI_Coordinate", "最小值", None))
        self.label_6.setText(_translate("UI_Coordinate", "最大值", None))
        self.label_2.setText(_translate("UI_Coordinate", "Y轴", None))
        self.label_5.setText(_translate("UI_Coordinate", "最小值", None))
        self.label_4.setText(_translate("UI_Coordinate", "最大值", None))
        self.xyset_ok.setText(_translate("UI_Coordinate", "确定", None))
        self.xyset_cancel.setText(_translate("UI_Coordinate", "取消", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UI_Coordinate = QtGui.QDialog()
    ui = Ui_UI_Coordinate()
    ui.setupUi(UI_Coordinate)
    UI_Coordinate.show()
    sys.exit(app.exec_())

