# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\set518p.ui'
#
# Created: Thu Dec 24 22:33:55 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/518.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_17 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(40)
        self.verticalLayout_16.setContentsMargins(20, 20, 20, 30)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(20)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.up_meas = QtGui.QCheckBox(self.groupBox)
        self.up_meas.setChecked(False)
        self.up_meas.setObjectName(_fromUtf8("up_meas"))
        self.horizontalLayout_21.addWidget(self.up_meas)
        self.down_meas = QtGui.QCheckBox(self.groupBox)
        self.down_meas.setObjectName(_fromUtf8("down_meas"))
        self.horizontalLayout_21.addWidget(self.down_meas)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setContentsMargins(20, 10, 10, 10)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.continuous = QtGui.QCheckBox(self.groupBox_2)
        self.continuous.setObjectName(_fromUtf8("continuous"))
        self.horizontalLayout_20.addWidget(self.continuous)
        self.segment = QtGui.QCheckBox(self.groupBox_2)
        self.segment.setCheckable(True)
        self.segment.setChecked(True)
        self.segment.setObjectName(_fromUtf8("segment"))
        self.horizontalLayout_20.addWidget(self.segment)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setSpacing(20)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setMargin(10)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(222, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.start_temp = QtGui.QLineEdit(self.groupBox_3)
        self.start_temp.setMinimumSize(QtCore.QSize(158, 20))
        self.start_temp.setObjectName(_fromUtf8("start_temp"))
        self.horizontalLayout.addWidget(self.start_temp)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_19.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label3 = QtGui.QLabel(self.groupBox_3)
        self.label3.setMinimumSize(QtCore.QSize(223, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.verticalLayout.addWidget(self.label3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.end_temp = QtGui.QLineEdit(self.groupBox_3)
        self.end_temp.setMinimumSize(QtCore.QSize(0, 20))
        self.end_temp.setObjectName(_fromUtf8("end_temp"))
        self.horizontalLayout_2.addWidget(self.end_temp)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.up_slope = QtGui.QLineEdit(self.groupBox_3)
        self.up_slope.setObjectName(_fromUtf8("up_slope"))
        self.horizontalLayout_3.addWidget(self.up_slope)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(223, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_9.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.down_slope = QtGui.QLineEdit(self.groupBox_3)
        self.down_slope.setObjectName(_fromUtf8("down_slope"))
        self.horizontalLayout_4.addWidget(self.down_slope)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_4.addWidget(self.label_23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(222, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.interval = QtGui.QLineEdit(self.groupBox_3)
        self.interval.setObjectName(_fromUtf8("interval"))
        self.horizontalLayout_5.addWidget(self.interval)
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_5.addWidget(self.label_24)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setMinimumSize(QtCore.QSize(223, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.critical_temp = QtGui.QLineEdit(self.groupBox_3)
        self.critical_temp.setObjectName(_fromUtf8("critical_temp"))
        self.horizontalLayout_9.addWidget(self.critical_temp)
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_9.addWidget(self.label_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setMinimumSize(QtCore.QSize(222, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.low_offset = QtGui.QLineEdit(self.groupBox_3)
        self.low_offset.setObjectName(_fromUtf8("low_offset"))
        self.horizontalLayout_10.addWidget(self.low_offset)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_10.addWidget(self.label_27)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(223, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.high_offset = QtGui.QLineEdit(self.groupBox_3)
        self.high_offset.setObjectName(_fromUtf8("high_offset"))
        self.horizontalLayout_6.addWidget(self.high_offset)
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_6.addWidget(self.label_25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(222, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.constant_time = QtGui.QLineEdit(self.groupBox_3)
        self.constant_time.setObjectName(_fromUtf8("constant_time"))
        self.horizontalLayout_7.addWidget(self.constant_time)
        self.label_39 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_7.addWidget(self.label_39)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setMinimumSize(QtCore.QSize(223, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.meas_times = QtGui.QLineEdit(self.groupBox_3)
        self.meas_times.setMinimumSize(QtCore.QSize(0, 20))
        self.meas_times.setObjectName(_fromUtf8("meas_times"))
        self.verticalLayout_4.addWidget(self.meas_times)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_14.addLayout(self.verticalLayout_11)
        self.verticalLayout_15.addWidget(self.groupBox_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_15)
        self.table_temp = QtGui.QTableWidget(Dialog)
        self.table_temp.setMaximumSize(QtCore.QSize(181, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.table_temp.setFont(font)
        self.table_temp.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_temp.setAlternatingRowColors(True)
        self.table_temp.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_temp.setObjectName(_fromUtf8("table_temp"))
        self.table_temp.setColumnCount(1)
        self.table_temp.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.table_temp.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table_temp.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_temp.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_temp.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.table_temp.setItem(2, 0, item)
        self.horizontalLayout_17.addWidget(self.table_temp)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_15.addWidget(self.label)
        self.now_temp = QtGui.QLineEdit(Dialog)
        self.now_temp.setEnabled(False)
        self.now_temp.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.now_temp.setFont(font)
        self.now_temp.setReadOnly(False)
        self.now_temp.setObjectName(_fromUtf8("now_temp"))
        self.horizontalLayout_15.addWidget(self.now_temp)
        self.label_54 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_15.addWidget(self.label_54)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.temp_confirm = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_confirm.setFont(font)
        self.temp_confirm.setObjectName(_fromUtf8("temp_confirm"))
        self.horizontalLayout_14.addWidget(self.temp_confirm)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.temp_cancel = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_cancel.setFont(font)
        self.temp_cancel.setObjectName(_fromUtf8("temp_cancel"))
        self.horizontalLayout_14.addWidget(self.temp_cancel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.temp_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "温度设置", None))
        self.groupBox.setTitle(_translate("Dialog", "测试序列", None))
        self.up_meas.setText(_translate("Dialog", "升温测量", None))
        self.down_meas.setText(_translate("Dialog", "降温测量", None))
        self.groupBox_2.setTitle(_translate("Dialog", "升温方式", None))
        self.continuous.setText(_translate("Dialog", "连续升温", None))
        self.segment.setText(_translate("Dialog", "分段升温", None))
        self.groupBox_3.setTitle(_translate("Dialog", "测量参数", None))
        self.label_2.setText(_translate("Dialog", "起始测量温度", None))
        self.start_temp.setText(_translate("Dialog", "100", None))
        self.label_10.setText(_translate("Dialog", "℃", None))
        self.label3.setText(_translate("Dialog", "终止测量温度", None))
        self.end_temp.setText(_translate("Dialog", "500", None))
        self.label_11.setText(_translate("Dialog", "℃", None))
        self.label_4.setText(_translate("Dialog", "升温斜率", None))
        self.up_slope.setText(_translate("Dialog", "10", None))
        self.label_12.setText(_translate("Dialog", "℃/min", None))
        self.label_5.setText(_translate("Dialog", "降温斜率", None))
        self.down_slope.setText(_translate("Dialog", "10", None))
        self.label_23.setText(_translate("Dialog", "℃/min", None))
        self.label_6.setText(_translate("Dialog", "采样间隔", None))
        self.interval.setText(_translate("Dialog", "50", None))
        self.label_24.setText(_translate("Dialog", "℃", None))
        self.label_13.setText(_translate("Dialog", "临界温度", None))
        self.critical_temp.setText(_translate("Dialog", "300", None))
        self.label_26.setText(_translate("Dialog", "℃", None))
        self.label_14.setText(_translate("Dialog", "低温段偏差范围", None))
        self.low_offset.setText(_translate("Dialog", "0", None))
        self.label_27.setText(_translate("Dialog", "℃", None))
        self.label_7.setText(_translate("Dialog", "高温偏差范围", None))
        self.high_offset.setText(_translate("Dialog", "0", None))
        self.label_25.setText(_translate("Dialog", "℃", None))
        self.label_8.setText(_translate("Dialog", "测量点恒温时间", None))
        self.constant_time.setText(_translate("Dialog", "10", None))
        self.label_39.setText(_translate("Dialog", "S", None))
        self.label_9.setText(_translate("Dialog", "温度点测量次数", None))
        self.meas_times.setText(_translate("Dialog", "5", None))
        item = self.table_temp.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1", None))
        item = self.table_temp.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2", None))
        item = self.table_temp.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3", None))
        item = self.table_temp.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4", None))
        item = self.table_temp.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5", None))
        item = self.table_temp.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6", None))
        item = self.table_temp.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7", None))
        item = self.table_temp.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8", None))
        item = self.table_temp.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "10", None))
        item = self.table_temp.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测量点温度/℃", None))
        __sortingEnabled = self.table_temp.isSortingEnabled()
        self.table_temp.setSortingEnabled(False)
        self.table_temp.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "当前温度", None))
        self.label_54.setText(_translate("Dialog", "℃", None))
        self.temp_confirm.setText(_translate("Dialog", "保存", None))
        self.temp_cancel.setText(_translate("Dialog", "退出", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

