# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\system_set.ui'
#
# Created: Sat Mar 05 20:54:17 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt4 import QtCore, QtGui
from AT_mplCanvas import AT_CanvasWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sys_set_ui(object):
    def setupUi(self, sys_set_ui):
        sys_set_ui.setObjectName(_fromUtf8("sys_set_ui"))
        sys_set_ui.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sys_set_ui.sizePolicy().hasHeightForWidth())
        sys_set_ui.setSizePolicy(sizePolicy)
        sys_set_ui.setMinimumSize(QtCore.QSize(800, 600))
        sys_set_ui.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        sys_set_ui.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/25.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sys_set_ui.setWindowIcon(icon)
        sys_set_ui.setStatusTip(_fromUtf8(""))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(sys_set_ui)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setMargin(10)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tabWidget = QtGui.QTabWidget(sys_set_ui)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.sys_test = QtGui.QWidget()
        self.sys_test.setObjectName(_fromUtf8("sys_test"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.sys_test)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setMargin(10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox = QtGui.QGroupBox(self.sys_test)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_17.addWidget(self.label_9)
        self.com_2400 = QtGui.QComboBox(self.groupBox)
        self.com_2400.setMinimumSize(QtCore.QSize(184, 22))
        self.com_2400.setMaximumSize(QtCore.QSize(184, 22))
        self.com_2400.setObjectName(_fromUtf8("com_2400"))
        self.com_2400.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.com_2400)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_15.addWidget(self.label_30)
        self.com_pcb = QtGui.QComboBox(self.groupBox)
        self.com_pcb.setObjectName(_fromUtf8("com_pcb"))
        self.com_pcb.addItem(_fromUtf8(""))
        self.com_pcb.addItem(_fromUtf8(""))
        self.com_pcb.addItem(_fromUtf8(""))
        self.com_pcb.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.com_pcb)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_40.addWidget(self.label_31)
        self.baud_pcb = QtGui.QComboBox(self.groupBox)
        self.baud_pcb.setObjectName(_fromUtf8("baud_pcb"))
        self.baud_pcb.addItem(_fromUtf8(""))
        self.baud_pcb.addItem(_fromUtf8(""))
        self.baud_pcb.addItem(_fromUtf8(""))
        self.horizontalLayout_40.addWidget(self.baud_pcb)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_40)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_12.addWidget(self.label)
        self.com_518p = QtGui.QComboBox(self.groupBox)
        self.com_518p.setObjectName(_fromUtf8("com_518p"))
        self.com_518p.addItem(_fromUtf8(""))
        self.com_518p.addItem(_fromUtf8(""))
        self.com_518p.addItem(_fromUtf8(""))
        self.com_518p.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.com_518p)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.baud_518p = QtGui.QComboBox(self.groupBox)
        self.baud_518p.setObjectName(_fromUtf8("baud_518p"))
        self.baud_518p.addItem(_fromUtf8(""))
        self.baud_518p.addItem(_fromUtf8(""))
        self.baud_518p.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.baud_518p)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(104, 19))
        self.label_2.setMaximumSize(QtCore.QSize(104, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        self.com_flowmeter = QtGui.QComboBox(self.groupBox)
        self.com_flowmeter.setMinimumSize(QtCore.QSize(58, 16))
        self.com_flowmeter.setMaximumSize(QtCore.QSize(58, 16))
        self.com_flowmeter.setObjectName(_fromUtf8("com_flowmeter"))
        self.com_flowmeter.addItem(_fromUtf8(""))
        self.com_flowmeter.addItem(_fromUtf8(""))
        self.com_flowmeter.addItem(_fromUtf8(""))
        self.com_flowmeter.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.com_flowmeter)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(48, 16))
        self.label_8.setMaximumSize(QtCore.QSize(48, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        self.baud_flowmeter = QtGui.QComboBox(self.groupBox)
        self.baud_flowmeter.setMinimumSize(QtCore.QSize(66, 19))
        self.baud_flowmeter.setMaximumSize(QtCore.QSize(66, 19))
        self.baud_flowmeter.setObjectName(_fromUtf8("baud_flowmeter"))
        self.baud_flowmeter.addItem(_fromUtf8(""))
        self.baud_flowmeter.addItem(_fromUtf8(""))
        self.baud_flowmeter.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.baud_flowmeter)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_36.addWidget(self.label_27)
        self.range1 = QtGui.QComboBox(self.groupBox)
        self.range1.setMinimumSize(QtCore.QSize(60, 19))
        self.range1.setMaximumSize(QtCore.QSize(60, 19))
        self.range1.setObjectName(_fromUtf8("range1"))
        self.range1.addItem(_fromUtf8(""))
        self.range1.addItem(_fromUtf8(""))
        self.range1.addItem(_fromUtf8(""))
        self.horizontalLayout_36.addWidget(self.range1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_36.addWidget(self.label_6)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_37.addWidget(self.label_28)
        self.range2 = QtGui.QComboBox(self.groupBox)
        self.range2.setMinimumSize(QtCore.QSize(60, 19))
        self.range2.setMaximumSize(QtCore.QSize(60, 19))
        self.range2.setObjectName(_fromUtf8("range2"))
        self.range2.addItem(_fromUtf8(""))
        self.range2.addItem(_fromUtf8(""))
        self.range2.addItem(_fromUtf8(""))
        self.horizontalLayout_37.addWidget(self.range2)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_37.addWidget(self.label_7)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_38.addWidget(self.label_29)
        self.range3 = QtGui.QComboBox(self.groupBox)
        self.range3.setMinimumSize(QtCore.QSize(60, 19))
        self.range3.setMaximumSize(QtCore.QSize(60, 19))
        self.range3.setObjectName(_fromUtf8("range3"))
        self.range3.addItem(_fromUtf8(""))
        self.range3.addItem(_fromUtf8(""))
        self.range3.addItem(_fromUtf8(""))
        self.horizontalLayout_38.addWidget(self.range3)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_38.addWidget(self.label_25)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_38)
        self.verticalLayout_5.addLayout(self.horizontalLayout_35)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.sys_test)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.pcb_ctrl_obj = QtGui.QComboBox(self.groupBox_2)
        self.pcb_ctrl_obj.setObjectName(_fromUtf8("pcb_ctrl_obj"))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.pcb_ctrl_obj.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.pcb_ctrl_obj)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.pcb_ctrl_return = QtGui.QLineEdit(self.groupBox_2)
        self.pcb_ctrl_return.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcb_ctrl_return.sizePolicy().hasHeightForWidth())
        self.pcb_ctrl_return.setSizePolicy(sizePolicy)
        self.pcb_ctrl_return.setObjectName(_fromUtf8("pcb_ctrl_return"))
        self.horizontalLayout_6.addWidget(self.pcb_ctrl_return)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.sys_test)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_25.addWidget(self.label_18)
        self.flowmeter_addr = QtGui.QComboBox(self.groupBox_4)
        self.flowmeter_addr.setObjectName(_fromUtf8("flowmeter_addr"))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.flowmeter_addr.addItem(_fromUtf8(""))
        self.horizontalLayout_25.addWidget(self.flowmeter_addr)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_19.addWidget(self.label_13)
        self.flowmeter_para = QtGui.QComboBox(self.groupBox_4)
        self.flowmeter_para.setObjectName(_fromUtf8("flowmeter_para"))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.flowmeter_para.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.flowmeter_para)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(20)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.flowmeter_read = QtGui.QPushButton(self.groupBox_4)
        self.flowmeter_read.setObjectName(_fromUtf8("flowmeter_read"))
        self.horizontalLayout_21.addWidget(self.flowmeter_read)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_21.addWidget(self.label_14)
        self.flowmeter_readpara = QtGui.QLineEdit(self.groupBox_4)
        self.flowmeter_readpara.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowmeter_readpara.sizePolicy().hasHeightForWidth())
        self.flowmeter_readpara.setSizePolicy(sizePolicy)
        self.flowmeter_readpara.setObjectName(_fromUtf8("flowmeter_readpara"))
        self.horizontalLayout_21.addWidget(self.flowmeter_readpara)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.flowmeter_write = QtGui.QPushButton(self.groupBox_4)
        self.flowmeter_write.setObjectName(_fromUtf8("flowmeter_write"))
        self.horizontalLayout_22.addWidget(self.flowmeter_write)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_22.addWidget(self.label_15)
        self.flowmeter_writepara = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowmeter_writepara.sizePolicy().hasHeightForWidth())
        self.flowmeter_writepara.setSizePolicy(sizePolicy)
        self.flowmeter_writepara.setObjectName(_fromUtf8("flowmeter_writepara"))
        self.horizontalLayout_22.addWidget(self.flowmeter_writepara)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_22)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.sys_test)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_31.addWidget(self.label_23)
        self.ai518p_addr = QtGui.QComboBox(self.groupBox_3)
        self.ai518p_addr.setObjectName(_fromUtf8("ai518p_addr"))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.ai518p_addr.addItem(_fromUtf8(""))
        self.horizontalLayout_31.addWidget(self.ai518p_addr)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.ai518p_para = QtGui.QComboBox(self.groupBox_3)
        self.ai518p_para.setObjectName(_fromUtf8("ai518p_para"))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.ai518p_para.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.ai518p_para)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ai518p_read = QtGui.QPushButton(self.groupBox_3)
        self.ai518p_read.setObjectName(_fromUtf8("ai518p_read"))
        self.horizontalLayout_2.addWidget(self.ai518p_read)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.ai518p_read_para = QtGui.QLineEdit(self.groupBox_3)
        self.ai518p_read_para.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ai518p_read_para.sizePolicy().hasHeightForWidth())
        self.ai518p_read_para.setSizePolicy(sizePolicy)
        self.ai518p_read_para.setObjectName(_fromUtf8("ai518p_read_para"))
        self.horizontalLayout_2.addWidget(self.ai518p_read_para)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ai518p_write = QtGui.QPushButton(self.groupBox_3)
        self.ai518p_write.setObjectName(_fromUtf8("ai518p_write"))
        self.horizontalLayout_3.addWidget(self.ai518p_write)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.ai518p_write_para = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ai518p_write_para.sizePolicy().hasHeightForWidth())
        self.ai518p_write_para.setSizePolicy(sizePolicy)
        self.ai518p_write_para.setObjectName(_fromUtf8("ai518p_write_para"))
        self.horizontalLayout_3.addWidget(self.ai518p_write_para)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.sys_test, _fromUtf8(""))
        self.restore518p = QtGui.QWidget()
        self.restore518p.setObjectName(_fromUtf8("restore518p"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.restore518p)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setMargin(10)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tableWidget = QtGui.QTableWidget(self.restore518p)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(13)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.restore_518p = QtGui.QPushButton(self.restore518p)
        self.restore_518p.setObjectName(_fromUtf8("restore_518p"))
        self.horizontalLayout_16.addWidget(self.restore_518p)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.restore518p, _fromUtf8(""))
        self.auto_pid = QtGui.QWidget()
        self.auto_pid.setObjectName(_fromUtf8("auto_pid"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.auto_pid)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setMargin(10)
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setSpacing(10)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_16 = QtGui.QLabel(self.auto_pid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_45.addWidget(self.label_16)
        self.PID_temp = QtGui.QLineEdit(self.auto_pid)
        self.PID_temp.setMaximumSize(QtCore.QSize(16777215, 22))
        self.PID_temp.setObjectName(_fromUtf8("PID_temp"))
        self.horizontalLayout_45.addWidget(self.PID_temp)
        self.label_17 = QtGui.QLabel(self.auto_pid)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_45.addWidget(self.label_17)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_45)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem7)
        self.start_AT = QtGui.QPushButton(self.auto_pid)
        self.start_AT.setObjectName(_fromUtf8("start_AT"))
        self.horizontalLayout_50.addWidget(self.start_AT)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem8)
        self.stop_AT = QtGui.QPushButton(self.auto_pid)
        self.stop_AT.setObjectName(_fromUtf8("stop_AT"))
        self.horizontalLayout_50.addWidget(self.stop_AT)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setMargin(10)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(10)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_20 = QtGui.QLabel(self.auto_pid)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_23.addWidget(self.label_20)
        self.now_PV = QtGui.QLineEdit(self.auto_pid)
        self.now_PV.setEnabled(False)
        self.now_PV.setMaximumSize(QtCore.QSize(16777215, 22))
        self.now_PV.setObjectName(_fromUtf8("now_PV"))
        self.horizontalLayout_23.addWidget(self.now_PV)
        self.label_19 = QtGui.QLabel(self.auto_pid)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_23.addWidget(self.label_19)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_23)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem10)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(10)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_22 = QtGui.QLabel(self.auto_pid)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_24.addWidget(self.label_22)
        self.now_SV = QtGui.QLineEdit(self.auto_pid)
        self.now_SV.setEnabled(False)
        self.now_SV.setMaximumSize(QtCore.QSize(16777215, 22))
        self.now_SV.setObjectName(_fromUtf8("now_SV"))
        self.horizontalLayout_24.addWidget(self.now_SV)
        self.label_21 = QtGui.QLabel(self.auto_pid)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_24.addWidget(self.label_21)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_24)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem11)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(10)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_36 = QtGui.QLabel(self.auto_pid)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_26.addWidget(self.label_36)
        self.now_temp = QtGui.QLineEdit(self.auto_pid)
        self.now_temp.setEnabled(False)
        self.now_temp.setMaximumSize(QtCore.QSize(16777215, 22))
        self.now_temp.setObjectName(_fromUtf8("now_temp"))
        self.horizontalLayout_26.addWidget(self.now_temp)
        self.label_24 = QtGui.QLabel(self.auto_pid)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_26.addWidget(self.label_24)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_26)
        self.verticalLayout_13.addLayout(self.horizontalLayout_48)
        self.AT_MPL = AT_CanvasWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AT_MPL.sizePolicy().hasHeightForWidth())
        self.AT_MPL.setSizePolicy(sizePolicy)
        self.AT_MPL.setMinimumSize(QtCore.QSize(750, 400))
        self.AT_MPL.setMaximumSize(QtCore.QSize(750, 400))
        self.AT_MPL.setObjectName(_fromUtf8("AT_MPL"))
        self.verticalLayout_13.addWidget(self.AT_MPL)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(10)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_37 = QtGui.QLabel(self.auto_pid)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_27.addWidget(self.label_37)
        self.para_M5 = QtGui.QLineEdit(self.auto_pid)
        self.para_M5.setEnabled(False)
        self.para_M5.setMaximumSize(QtCore.QSize(16777215, 22))
        self.para_M5.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.para_M5.setObjectName(_fromUtf8("para_M5"))
        self.horizontalLayout_27.addWidget(self.para_M5)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem12)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_27)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem13)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_39 = QtGui.QLabel(self.auto_pid)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_29.addWidget(self.label_39)
        self.para_t = QtGui.QLineEdit(self.auto_pid)
        self.para_t.setEnabled(False)
        self.para_t.setMaximumSize(QtCore.QSize(16777215, 22))
        self.para_t.setObjectName(_fromUtf8("para_t"))
        self.horizontalLayout_29.addWidget(self.para_t)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_29)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem14)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(10)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem15)
        self.label_38 = QtGui.QLabel(self.auto_pid)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_28.addWidget(self.label_38)
        self.para_P = QtGui.QLineEdit(self.auto_pid)
        self.para_P.setEnabled(False)
        self.para_P.setMaximumSize(QtCore.QSize(16777215, 22))
        self.para_P.setObjectName(_fromUtf8("para_P"))
        self.horizontalLayout_28.addWidget(self.para_P)
        self.horizontalLayout_47.addLayout(self.horizontalLayout_28)
        self.verticalLayout_13.addLayout(self.horizontalLayout_47)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.auto_pid, _fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.tabWidget)

        self.retranslateUi(sys_set_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sys_set_ui)

    def retranslateUi(self, sys_set_ui):
        sys_set_ui.setWindowTitle(_translate("sys_set_ui", "系统设置", None))
        self.groupBox.setTitle(_translate("sys_set_ui", "通讯参数设置", None))
        self.label_9.setText(_translate("sys_set_ui", "阻抗仪通讯I/O", None))
        self.label_30.setText(_translate("sys_set_ui", "控制板通讯I/O", None))
        self.com_pcb.setItemText(0, _translate("sys_set_ui", "COM1", None))
        self.com_pcb.setItemText(1, _translate("sys_set_ui", "COM2", None))
        self.com_pcb.setItemText(2, _translate("sys_set_ui", "COM3", None))
        self.com_pcb.setItemText(3, _translate("sys_set_ui", "COM4", None))
        self.label_31.setText(_translate("sys_set_ui", "波特率", None))
        self.baud_pcb.setItemText(0, _translate("sys_set_ui", "9600", None))
        self.baud_pcb.setItemText(1, _translate("sys_set_ui", "19200", None))
        self.baud_pcb.setItemText(2, _translate("sys_set_ui", "38400", None))
        self.label.setText(_translate("sys_set_ui", "温控仪通讯I/O", None))
        self.com_518p.setItemText(0, _translate("sys_set_ui", "COM1", None))
        self.com_518p.setItemText(1, _translate("sys_set_ui", "COM2", None))
        self.com_518p.setItemText(2, _translate("sys_set_ui", "COM3", None))
        self.com_518p.setItemText(3, _translate("sys_set_ui", "COM4", None))
        self.label_3.setText(_translate("sys_set_ui", "波特率", None))
        self.baud_518p.setItemText(0, _translate("sys_set_ui", "9600", None))
        self.baud_518p.setItemText(1, _translate("sys_set_ui", "19200", None))
        self.baud_518p.setItemText(2, _translate("sys_set_ui", "38400", None))
        self.label_2.setText(_translate("sys_set_ui", "流量计通讯I/O", None))
        self.com_flowmeter.setItemText(0, _translate("sys_set_ui", "COM1", None))
        self.com_flowmeter.setItemText(1, _translate("sys_set_ui", "COM2", None))
        self.com_flowmeter.setItemText(2, _translate("sys_set_ui", "COM3", None))
        self.com_flowmeter.setItemText(3, _translate("sys_set_ui", "COM4", None))
        self.label_8.setText(_translate("sys_set_ui", "波特率", None))
        self.baud_flowmeter.setItemText(0, _translate("sys_set_ui", "9600", None))
        self.baud_flowmeter.setItemText(1, _translate("sys_set_ui", "19200", None))
        self.baud_flowmeter.setItemText(2, _translate("sys_set_ui", "38400", None))
        self.label_27.setText(_translate("sys_set_ui", "量程1", None))
        self.range1.setItemText(0, _translate("sys_set_ui", "50", None))
        self.range1.setItemText(1, _translate("sys_set_ui", "500", None))
        self.range1.setItemText(2, _translate("sys_set_ui", "2000", None))
        self.label_6.setText(_translate("sys_set_ui", "mL", None))
        self.label_28.setText(_translate("sys_set_ui", "量程2", None))
        self.range2.setItemText(0, _translate("sys_set_ui", "50", None))
        self.range2.setItemText(1, _translate("sys_set_ui", "500", None))
        self.range2.setItemText(2, _translate("sys_set_ui", "2000", None))
        self.label_7.setText(_translate("sys_set_ui", "mL", None))
        self.label_29.setText(_translate("sys_set_ui", "量程3", None))
        self.range3.setItemText(0, _translate("sys_set_ui", "50", None))
        self.range3.setItemText(1, _translate("sys_set_ui", "500", None))
        self.range3.setItemText(2, _translate("sys_set_ui", "2000", None))
        self.label_25.setText(_translate("sys_set_ui", "mL", None))
        self.groupBox_2.setTitle(_translate("sys_set_ui", "电路板控制", None))
        self.label_4.setText(_translate("sys_set_ui", "电路板控制监测", None))
        self.pcb_ctrl_obj.setItemText(0, _translate("sys_set_ui", "充气阀开", None))
        self.pcb_ctrl_obj.setItemText(1, _translate("sys_set_ui", "充气阀关", None))
        self.pcb_ctrl_obj.setItemText(2, _translate("sys_set_ui", "放气阀开", None))
        self.pcb_ctrl_obj.setItemText(3, _translate("sys_set_ui", "放气阀关", None))
        self.pcb_ctrl_obj.setItemText(4, _translate("sys_set_ui", "真空阀开", None))
        self.pcb_ctrl_obj.setItemText(5, _translate("sys_set_ui", "真空阀关", None))
        self.pcb_ctrl_obj.setItemText(6, _translate("sys_set_ui", "真空泵开", None))
        self.pcb_ctrl_obj.setItemText(7, _translate("sys_set_ui", "真空泵关", None))
        self.label_5.setText(_translate("sys_set_ui", "返回值", None))
        self.groupBox_4.setTitle(_translate("sys_set_ui", "流量计读写监测", None))
        self.label_18.setText(_translate("sys_set_ui", "仪表地址", None))
        self.flowmeter_addr.setItemText(0, _translate("sys_set_ui", "1", None))
        self.flowmeter_addr.setItemText(1, _translate("sys_set_ui", "2", None))
        self.flowmeter_addr.setItemText(2, _translate("sys_set_ui", "3", None))
        self.flowmeter_addr.setItemText(3, _translate("sys_set_ui", "4", None))
        self.flowmeter_addr.setItemText(4, _translate("sys_set_ui", "5", None))
        self.flowmeter_addr.setItemText(5, _translate("sys_set_ui", "6", None))
        self.flowmeter_addr.setItemText(6, _translate("sys_set_ui", "7", None))
        self.flowmeter_addr.setItemText(7, _translate("sys_set_ui", "8", None))
        self.flowmeter_addr.setItemText(8, _translate("sys_set_ui", "9", None))
        self.flowmeter_addr.setItemText(9, _translate("sys_set_ui", "10", None))
        self.flowmeter_addr.setItemText(10, _translate("sys_set_ui", "11", None))
        self.flowmeter_addr.setItemText(11, _translate("sys_set_ui", "12", None))
        self.flowmeter_addr.setItemText(12, _translate("sys_set_ui", "13", None))
        self.flowmeter_addr.setItemText(13, _translate("sys_set_ui", "14", None))
        self.flowmeter_addr.setItemText(14, _translate("sys_set_ui", "15", None))
        self.label_13.setText(_translate("sys_set_ui", "参数代号", None))
        self.flowmeter_para.setItemText(0, _translate("sys_set_ui", "关闭", None))
        self.flowmeter_para.setItemText(1, _translate("sys_set_ui", "阀控", None))
        self.flowmeter_para.setItemText(2, _translate("sys_set_ui", "清洗", None))
        self.flowmeter_para.setItemText(3, _translate("sys_set_ui", "模拟/数字切换", None))
        self.flowmeter_para.setItemText(4, _translate("sys_set_ui", "自动调零", None))
        self.flowmeter_para.setItemText(5, _translate("sys_set_ui", "单位", None))
        self.flowmeter_para.setItemText(6, _translate("sys_set_ui", "显示流量", None))
        self.flowmeter_para.setItemText(7, _translate("sys_set_ui", "设定流量", None))
        self.flowmeter_para.setItemText(8, _translate("sys_set_ui", "流量值量程", None))
        self.flowmeter_para.setItemText(9, _translate("sys_set_ui", "零偏值", None))
        self.flowmeter_read.setText(_translate("sys_set_ui", "读操作", None))
        self.label_14.setText(_translate("sys_set_ui", "读取参数", None))
        self.flowmeter_write.setText(_translate("sys_set_ui", "写操作", None))
        self.label_15.setText(_translate("sys_set_ui", "写入参数", None))
        self.groupBox_3.setTitle(_translate("sys_set_ui", "温控仪读写监测", None))
        self.label_23.setText(_translate("sys_set_ui", "仪表地址", None))
        self.ai518p_addr.setItemText(0, _translate("sys_set_ui", "1", None))
        self.ai518p_addr.setItemText(1, _translate("sys_set_ui", "2", None))
        self.ai518p_addr.setItemText(2, _translate("sys_set_ui", "3", None))
        self.ai518p_addr.setItemText(3, _translate("sys_set_ui", "4", None))
        self.ai518p_addr.setItemText(4, _translate("sys_set_ui", "5", None))
        self.ai518p_addr.setItemText(5, _translate("sys_set_ui", "6", None))
        self.ai518p_addr.setItemText(6, _translate("sys_set_ui", "7", None))
        self.ai518p_addr.setItemText(7, _translate("sys_set_ui", "8", None))
        self.ai518p_addr.setItemText(8, _translate("sys_set_ui", "9", None))
        self.ai518p_addr.setItemText(9, _translate("sys_set_ui", "10", None))
        self.ai518p_addr.setItemText(10, _translate("sys_set_ui", "11", None))
        self.ai518p_addr.setItemText(11, _translate("sys_set_ui", "12", None))
        self.ai518p_addr.setItemText(12, _translate("sys_set_ui", "13", None))
        self.ai518p_addr.setItemText(13, _translate("sys_set_ui", "14", None))
        self.ai518p_addr.setItemText(14, _translate("sys_set_ui", "15", None))
        self.label_10.setText(_translate("sys_set_ui", "参数代号", None))
        self.ai518p_para.setItemText(0, _translate("sys_set_ui", "SV给定值/SteP程序段", None))
        self.ai518p_para.setItemText(1, _translate("sys_set_ui", "HIAL上限报警", None))
        self.ai518p_para.setItemText(2, _translate("sys_set_ui", "LoAL下限报警", None))
        self.ai518p_para.setItemText(3, _translate("sys_set_ui", "dHAL正偏差报警", None))
        self.ai518p_para.setItemText(4, _translate("sys_set_ui", "dLAL负偏差报警", None))
        self.ai518p_para.setItemText(5, _translate("sys_set_ui", "dF回差", None))
        self.ai518p_para.setItemText(6, _translate("sys_set_ui", "Ctrl控制方式", None))
        self.ai518p_para.setItemText(7, _translate("sys_set_ui", "M5保持参数", None))
        self.ai518p_para.setItemText(8, _translate("sys_set_ui", "P速率参数", None))
        self.ai518p_para.setItemText(9, _translate("sys_set_ui", "t滞后时间", None))
        self.ai518p_para.setItemText(10, _translate("sys_set_ui", "CtI控制周期", None))
        self.ai518p_para.setItemText(11, _translate("sys_set_ui", "Sn输入规格", None))
        self.ai518p_para.setItemText(12, _translate("sys_set_ui", "dIP小数点位置", None))
        self.ai518p_para.setItemText(13, _translate("sys_set_ui", "dIL输入下限显示值", None))
        self.ai518p_para.setItemText(14, _translate("sys_set_ui", "dIH输入上限显示值", None))
        self.ai518p_para.setItemText(15, _translate("sys_set_ui", "ALP报警输出定义", None))
        self.ai518p_para.setItemText(16, _translate("sys_set_ui", "Sc输入平移修正", None))
        self.ai518p_para.setItemText(17, _translate("sys_set_ui", "OP1输出方式", None))
        self.ai518p_para.setItemText(18, _translate("sys_set_ui", "oPL输出下限", None))
        self.ai518p_para.setItemText(19, _translate("sys_set_ui", "oPH输出上限", None))
        self.ai518p_para.setItemText(20, _translate("sys_set_ui", "CF功能选择", None))
        self.ai518p_para.setItemText(21, _translate("sys_set_ui", "仪表特征码/程序控制字（运行：0 暂停：4 停止：12）", None))
        self.ai518p_para.setItemText(22, _translate("sys_set_ui", "仪表地址（读/写）", None))
        self.ai518p_para.setItemText(23, _translate("sys_set_ui", "dL数字滤波", None))
        self.ai518p_para.setItemText(24, _translate("sys_set_ui", "run运行参数", None))
        self.ai518p_para.setItemText(25, _translate("sys_set_ui", "Loc参数封锁", None))
        self.ai518p_para.setItemText(26, _translate("sys_set_ui", "C01", None))
        self.ai518p_para.setItemText(27, _translate("sys_set_ui", "t01", None))
        self.ai518p_para.setItemText(28, _translate("sys_set_ui", "C02", None))
        self.ai518p_para.setItemText(29, _translate("sys_set_ui", "t02", None))
        self.ai518p_para.setItemText(30, _translate("sys_set_ui", "C03", None))
        self.ai518p_para.setItemText(31, _translate("sys_set_ui", "t03", None))
        self.ai518p_read.setText(_translate("sys_set_ui", "读操作", None))
        self.label_11.setText(_translate("sys_set_ui", "读取参数", None))
        self.ai518p_write.setText(_translate("sys_set_ui", "写操作", None))
        self.label_12.setText(_translate("sys_set_ui", "写入参数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sys_test), _translate("sys_set_ui", "硬件参数设置", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("sys_set_ui", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("sys_set_ui", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("sys_set_ui", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("sys_set_ui", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("sys_set_ui", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("sys_set_ui", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("sys_set_ui", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("sys_set_ui", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("sys_set_ui", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("sys_set_ui", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("sys_set_ui", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("sys_set_ui", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("sys_set_ui", "13", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("sys_set_ui", "参数名称", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("sys_set_ui", "参数值", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("sys_set_ui", "参数名称", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("sys_set_ui", "参数值", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("sys_set_ui", "SV给定值/Step程序段", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("sys_set_ui", "1", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("sys_set_ui", "dIL输入下限显示值", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("sys_set_ui", "0", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("sys_set_ui", "HIAL上限报警", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("sys_set_ui", "8000", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("sys_set_ui", "dIH输入上限显示值", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("sys_set_ui", "5000", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("sys_set_ui", "LoAL下限报警", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("sys_set_ui", "-1960", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("sys_set_ui", "ALP报警输出定义", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("sys_set_ui", "5543", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("sys_set_ui", "dHAL正偏差报警", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("sys_set_ui", "9999", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("sys_set_ui", "Sc输入平移修正", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("sys_set_ui", "0", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("sys_set_ui", "dLAL负偏差报警", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("sys_set_ui", "9999", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("sys_set_ui", "OP1输出方式", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("sys_set_ui", "0", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("sys_set_ui", "dF回差", None))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("sys_set_ui", "2", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("sys_set_ui", "oPL输出下限", None))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("sys_set_ui", "0", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("sys_set_ui", "Ctrl控制方式", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("sys_set_ui", "3", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("sys_set_ui", "oPH输出上限", None))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("sys_set_ui", "100", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("sys_set_ui", "M5保持参数", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("sys_set_ui", "50", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("sys_set_ui", "CF功能选择", None))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("sys_set_ui", "6", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("sys_set_ui", "P 速率参数", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("sys_set_ui", "65", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("sys_set_ui", "仪表特征码/程序控制字(运行:0 暂停:4 停止:12)", None))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("sys_set_ui", "12", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("sys_set_ui", "t滞后时间", None))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("sys_set_ui", "20", None))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("sys_set_ui", "仪表地址（读/写）", None))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("sys_set_ui", "1", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("sys_set_ui", "CtI控制周期", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("sys_set_ui", "2", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("sys_set_ui", "dL数字滤波", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("sys_set_ui", "10", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("sys_set_ui", "Sn输入规格", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("sys_set_ui", "0", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("sys_set_ui", "run运行参数", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("sys_set_ui", "27", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("sys_set_ui", "dIP小数点位置", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("sys_set_ui", "1", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("sys_set_ui", "Loc参数封锁", None))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("sys_set_ui", "808", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.restore_518p.setText(_translate("sys_set_ui", "一键恢复出厂设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.restore518p), _translate("sys_set_ui", "温控参数设置", None))
        self.label_16.setText(_translate("sys_set_ui", "PID整定温度", None))
        self.PID_temp.setText(_translate("sys_set_ui", "400", None))
        self.label_17.setText(_translate("sys_set_ui", "℃", None))
        self.start_AT.setText(_translate("sys_set_ui", "一键自整定", None))
        self.stop_AT.setText(_translate("sys_set_ui", "停止", None))
        self.label_20.setText(_translate("sys_set_ui", "测量值PV", None))
        self.label_19.setText(_translate("sys_set_ui", "℃", None))
        self.label_22.setText(_translate("sys_set_ui", "当前给定值SV", None))
        self.label_21.setText(_translate("sys_set_ui", "℃", None))
        self.label_36.setText(_translate("sys_set_ui", "当前温度", None))
        self.label_24.setText(_translate("sys_set_ui", "℃", None))
        self.label_37.setText(_translate("sys_set_ui", "M5保持参数", None))
        self.label_39.setText(_translate("sys_set_ui", "t滞后时间", None))
        self.label_38.setText(_translate("sys_set_ui", "P速率参数", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.auto_pid), _translate("sys_set_ui", "一键自整定", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    sys_set_ui = QtGui.QDialog()
    ui = Ui_sys_set_ui()
    ui.setupUi(sys_set_ui)
    sys_set_ui.show()
    sys.exit(app.exec_())

