# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\VI_spectrum\VI_main.ui'
#
# Created: Mon Jan 04 23:10:33 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from VI_mplCanvas import VI_CanvasWidget
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/27.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_11 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.VI_MPL = VI_CanvasWidget()
        self.VI_MPL.setMinimumSize(QtCore.QSize(480, 320))
        self.VI_MPL.setMaximumSize(QtCore.QSize(480, 320))
        self.VI_MPL.setObjectName(_fromUtf8("VI_MPL"))
        self.verticalLayout_4.addWidget(self.VI_MPL)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setMinimumSize(QtCore.QSize(480, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(480, 16777215))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_25.addWidget(self.label_22)
        self.now_v = QtGui.QLineEdit(self.groupBox_6)
        self.now_v.setReadOnly(True)
        self.now_v.setObjectName(_fromUtf8("now_v"))
        self.horizontalLayout_25.addWidget(self.now_v)
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_25.addWidget(self.label_10)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_26.addWidget(self.label_23)
        self.flow1 = QtGui.QLineEdit(self.groupBox_6)
        self.flow1.setReadOnly(True)
        self.flow1.setObjectName(_fromUtf8("flow1"))
        self.horizontalLayout_26.addWidget(self.flow1)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_26.addWidget(self.label_11)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_26)
        self.verticalLayout_16.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_28.addWidget(self.label_24)
        self.now_I = QtGui.QLineEdit(self.groupBox_6)
        self.now_I.setReadOnly(True)
        self.now_I.setObjectName(_fromUtf8("now_I"))
        self.horizontalLayout_28.addWidget(self.now_I)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_28.addWidget(self.label_12)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_34 = QtGui.QLabel(self.groupBox_6)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_29.addWidget(self.label_34)
        self.flow2 = QtGui.QLineEdit(self.groupBox_6)
        self.flow2.setReadOnly(True)
        self.flow2.setObjectName(_fromUtf8("flow2"))
        self.horizontalLayout_29.addWidget(self.flow2)
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_29.addWidget(self.label_25)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_29)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_35 = QtGui.QLabel(self.groupBox_6)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_31.addWidget(self.label_35)
        self.now_R = QtGui.QLineEdit(self.groupBox_6)
        self.now_R.setReadOnly(True)
        self.now_R.setObjectName(_fromUtf8("now_R"))
        self.horizontalLayout_31.addWidget(self.now_R)
        self.label_36 = QtGui.QLabel(self.groupBox_6)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_31.addWidget(self.label_36)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_37 = QtGui.QLabel(self.groupBox_6)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_32.addWidget(self.label_37)
        self.flow3 = QtGui.QLineEdit(self.groupBox_6)
        self.flow3.setReadOnly(True)
        self.flow3.setObjectName(_fromUtf8("flow3"))
        self.horizontalLayout_32.addWidget(self.flow3)
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_32.addWidget(self.label_38)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_32)
        self.verticalLayout_16.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_34.addWidget(self.label_39)
        self.now_T = QtGui.QLineEdit(self.groupBox_6)
        self.now_T.setMinimumSize(QtCore.QSize(121, 22))
        self.now_T.setMaximumSize(QtCore.QSize(121, 22))
        self.now_T.setReadOnly(True)
        self.now_T.setObjectName(_fromUtf8("now_T"))
        self.horizontalLayout_34.addWidget(self.now_T)
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_34.addWidget(self.label_2)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_35.addWidget(self.label_40)
        self.meas_time = QtGui.QLineEdit(self.groupBox_6)
        self.meas_time.setReadOnly(True)
        self.meas_time.setObjectName(_fromUtf8("meas_time"))
        self.horizontalLayout_35.addWidget(self.meas_time)
        self.label_41 = QtGui.QLabel(self.groupBox_6)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_35.addWidget(self.label_41)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.verticalLayout_16.addLayout(self.horizontalLayout_33)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_16 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        self.groupBox_16.setMinimumSize(QtCore.QSize(281, 120))
        self.groupBox_16.setMaximumSize(QtCore.QSize(281, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_28 = QtGui.QLabel(self.groupBox_16)
        self.label_28.setMinimumSize(QtCore.QSize(64, 22))
        self.label_28.setMaximumSize(QtCore.QSize(64, 22))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_36.addWidget(self.label_28)
        self.sample_id = QtGui.QLineEdit(self.groupBox_16)
        self.sample_id.setMinimumSize(QtCore.QSize(183, 22))
        self.sample_id.setMaximumSize(QtCore.QSize(183, 22))
        self.sample_id.setObjectName(_fromUtf8("sample_id"))
        self.horizontalLayout_36.addWidget(self.sample_id)
        self.verticalLayout_7.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_29 = QtGui.QLabel(self.groupBox_16)
        self.label_29.setMinimumSize(QtCore.QSize(64, 22))
        self.label_29.setMaximumSize(QtCore.QSize(64, 22))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_37.addWidget(self.label_29)
        self.save_path = QtGui.QLineEdit(self.groupBox_16)
        self.save_path.setMinimumSize(QtCore.QSize(149, 22))
        self.save_path.setMaximumSize(QtCore.QSize(149, 22))
        self.save_path.setObjectName(_fromUtf8("save_path"))
        self.horizontalLayout_37.addWidget(self.save_path)
        self.btn_savepath = QtGui.QPushButton(self.groupBox_16)
        self.btn_savepath.setMinimumSize(QtCore.QSize(30, 24))
        self.btn_savepath.setMaximumSize(QtCore.QSize(30, 24))
        self.btn_savepath.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/folder.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_savepath.setIcon(icon1)
        self.btn_savepath.setIconSize(QtCore.QSize(16, 16))
        self.btn_savepath.setObjectName(_fromUtf8("btn_savepath"))
        self.horizontalLayout_37.addWidget(self.btn_savepath)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_30 = QtGui.QLabel(self.groupBox_16)
        self.label_30.setMinimumSize(QtCore.QSize(36, 29))
        self.label_30.setMaximumSize(QtCore.QSize(36, 29))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_38.addWidget(self.label_30)
        self.sample_area = QtGui.QLineEdit(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_area.sizePolicy().hasHeightForWidth())
        self.sample_area.setSizePolicy(sizePolicy)
        self.sample_area.setMinimumSize(QtCore.QSize(40, 22))
        self.sample_area.setMaximumSize(QtCore.QSize(40, 22))
        self.sample_area.setObjectName(_fromUtf8("sample_area"))
        self.horizontalLayout_38.addWidget(self.sample_area)
        self.label_31 = QtGui.QLabel(self.groupBox_16)
        self.label_31.setMinimumSize(QtCore.QSize(32, 29))
        self.label_31.setMaximumSize(QtCore.QSize(32, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_38.addWidget(self.label_31)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_32 = QtGui.QLabel(self.groupBox_16)
        self.label_32.setMinimumSize(QtCore.QSize(36, 29))
        self.label_32.setMaximumSize(QtCore.QSize(36, 26))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_39.addWidget(self.label_32)
        self.sample_height = QtGui.QLineEdit(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_height.sizePolicy().hasHeightForWidth())
        self.sample_height.setSizePolicy(sizePolicy)
        self.sample_height.setMinimumSize(QtCore.QSize(40, 22))
        self.sample_height.setMaximumSize(QtCore.QSize(40, 22))
        self.sample_height.setObjectName(_fromUtf8("sample_height"))
        self.horizontalLayout_39.addWidget(self.sample_height)
        self.label_33 = QtGui.QLabel(self.groupBox_16)
        self.label_33.setMinimumSize(QtCore.QSize(23, 29))
        self.label_33.setMaximumSize(QtCore.QSize(23, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_39.addWidget(self.label_33)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_39)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.groupBox_16)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(281, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(281, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.no_gas = QtGui.QRadioButton(self.groupBox)
        self.no_gas.setChecked(True)
        self.no_gas.setObjectName(_fromUtf8("no_gas"))
        self.verticalLayout.addWidget(self.no_gas)
        self.gas_filled = QtGui.QRadioButton(self.groupBox)
        self.gas_filled.setObjectName(_fromUtf8("gas_filled"))
        self.verticalLayout.addWidget(self.gas_filled)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(281, 100))
        self.groupBox_4.setMaximumSize(QtCore.QSize(281, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.VI_2400_set = QtGui.QPushButton(self.groupBox_4)
        self.VI_2400_set.setObjectName(_fromUtf8("VI_2400_set"))
        self.horizontalLayout_6.addWidget(self.VI_2400_set)
        self.VI_518p_set = QtGui.QPushButton(self.groupBox_4)
        self.VI_518p_set.setObjectName(_fromUtf8("VI_518p_set"))
        self.horizontalLayout_6.addWidget(self.VI_518p_set)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.VI_gas_set = QtGui.QPushButton(self.groupBox_4)
        self.VI_gas_set.setEnabled(False)
        self.VI_gas_set.setObjectName(_fromUtf8("VI_gas_set"))
        self.horizontalLayout_12.addWidget(self.VI_gas_set)
        self.VI_XY_set = QtGui.QPushButton(self.groupBox_4)
        self.VI_XY_set.setObjectName(_fromUtf8("VI_XY_set"))
        self.horizontalLayout_12.addWidget(self.VI_XY_set)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(281, 80))
        self.groupBox_5.setMaximumSize(QtCore.QSize(281, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.VI_mode = QtGui.QRadioButton(self.groupBox_5)
        self.VI_mode.setChecked(True)
        self.VI_mode.setObjectName(_fromUtf8("VI_mode"))
        self.verticalLayout_5.addWidget(self.VI_mode)
        self.IV_mode = QtGui.QRadioButton(self.groupBox_5)
        self.IV_mode.setObjectName(_fromUtf8("IV_mode"))
        self.verticalLayout_5.addWidget(self.IV_mode)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.VI_start = QtGui.QPushButton(Dialog)
        self.VI_start.setObjectName(_fromUtf8("VI_start"))
        self.horizontalLayout_14.addWidget(self.VI_start)
        self.VI_stop = QtGui.QPushButton(Dialog)
        self.VI_stop.setObjectName(_fromUtf8("VI_stop"))
        self.horizontalLayout_14.addWidget(self.VI_stop)
        self.VI_save = QtGui.QPushButton(Dialog)
        self.VI_save.setObjectName(_fromUtf8("VI_save"))
        self.horizontalLayout_14.addWidget(self.VI_save)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(780, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(780, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.inst_sta = QtGui.QLabel(self.groupBox_3)
        self.inst_sta.setText(_fromUtf8(""))
        self.inst_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/noyb.png")))
        self.inst_sta.setObjectName(_fromUtf8("inst_sta"))
        self.horizontalLayout_4.addWidget(self.inst_sta)
        self.pcb_sta = QtGui.QLabel(self.groupBox_3)
        self.pcb_sta.setText(_fromUtf8(""))
        self.pcb_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/nodlb.png")))
        self.pcb_sta.setObjectName(_fromUtf8("pcb_sta"))
        self.horizontalLayout_4.addWidget(self.pcb_sta)
        self.ai518_sta = QtGui.QLabel(self.groupBox_3)
        self.ai518_sta.setText(_fromUtf8(""))
        self.ai518_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/nowky.png")))
        self.ai518_sta.setObjectName(_fromUtf8("ai518_sta"))
        self.horizontalLayout_4.addWidget(self.ai518_sta)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.sys_state = QtGui.QLineEdit(self.groupBox_3)
        self.sys_state.setEnabled(False)
        self.sys_state.setObjectName(_fromUtf8("sys_state"))
        self.horizontalLayout_11.addWidget(self.sys_state)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.valve1_sta = QtGui.QLabel(self.groupBox_3)
        self.valve1_sta.setText(_fromUtf8(""))
        self.valve1_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/guan.png")))
        self.valve1_sta.setObjectName(_fromUtf8("valve1_sta"))
        self.horizontalLayout_5.addWidget(self.valve1_sta)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.valve2_sta = QtGui.QLabel(self.groupBox_3)
        self.valve2_sta.setText(_fromUtf8(""))
        self.valve2_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/guan.png")))
        self.valve2_sta.setObjectName(_fromUtf8("valve2_sta"))
        self.horizontalLayout_3.addWidget(self.valve2_sta)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        self.valve3_sta = QtGui.QLabel(self.groupBox_3)
        self.valve3_sta.setText(_fromUtf8(""))
        self.valve3_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/guan.png")))
        self.valve3_sta.setObjectName(_fromUtf8("valve3_sta"))
        self.horizontalLayout_7.addWidget(self.valve3_sta)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.valve_clean_sta = QtGui.QLabel(self.groupBox_3)
        self.valve_clean_sta.setText(_fromUtf8(""))
        self.valve_clean_sta.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/guan.png")))
        self.valve_clean_sta.setObjectName(_fromUtf8("valve_clean_sta"))
        self.horizontalLayout_9.addWidget(self.valve_clean_sta)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/partulab.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_11.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "电压电流谱", None))
        self.groupBox_6.setTitle(_translate("Dialog", "测量参数", None))
        self.label_22.setText(_translate("Dialog", "当前电压", None))
        self.label_10.setText(_translate("Dialog", "V", None))
        self.label_23.setText(_translate("Dialog", "流量计1", None))
        self.label_11.setText(_translate("Dialog", "mL/min", None))
        self.label_24.setText(_translate("Dialog", "当前电流", None))
        self.label_12.setText(_translate("Dialog", "A", None))
        self.label_34.setText(_translate("Dialog", "流量计2", None))
        self.label_25.setText(_translate("Dialog", "mL/min", None))
        self.label_35.setText(_translate("Dialog", "当前阻值", None))
        self.label_36.setText(_translate("Dialog", "Ω", None))
        self.label_37.setText(_translate("Dialog", "流量计3", None))
        self.label_38.setText(_translate("Dialog", "mL/min", None))
        self.label_39.setText(_translate("Dialog", "当前温度", None))
        self.label_2.setText(_translate("Dialog", "℃", None))
        self.label_40.setText(_translate("Dialog", "测量时间", None))
        self.label_41.setText(_translate("Dialog", "S", None))
        self.groupBox_16.setTitle(_translate("Dialog", "样品信息", None))
        self.label_28.setText(_translate("Dialog", "样品标识", None))
        self.sample_id.setText(_translate("Dialog", "VI_test", None))
        self.label_29.setText(_translate("Dialog", "保存路径", None))
        self.save_path.setText(_translate("Dialog", "D:/", None))
        self.label_30.setText(_translate("Dialog", "面积", None))
        self.sample_area.setText(_translate("Dialog", "10", None))
        self.label_31.setText(_translate("Dialog", "mm^2", None))
        self.label_32.setText(_translate("Dialog", "厚度", None))
        self.sample_height.setText(_translate("Dialog", "5", None))
        self.label_33.setText(_translate("Dialog", "mm", None))
        self.groupBox.setTitle(_translate("Dialog", "功能设置", None))
        self.no_gas.setText(_translate("Dialog", "不充气测量", None))
        self.gas_filled.setText(_translate("Dialog", "充气测量", None))
        self.groupBox_4.setTitle(_translate("Dialog", "参数设置", None))
        self.VI_2400_set.setText(_translate("Dialog", "仪器设置", None))
        self.VI_518p_set.setText(_translate("Dialog", "温度设置", None))
        self.VI_gas_set.setText(_translate("Dialog", "气压控制", None))
        self.VI_XY_set.setText(_translate("Dialog", "XY坐标设置", None))
        self.groupBox_5.setTitle(_translate("Dialog", "曲线选择", None))
        self.VI_mode.setText(_translate("Dialog", "V-I曲线", None))
        self.IV_mode.setText(_translate("Dialog", "I-V曲线", None))
        self.VI_start.setText(_translate("Dialog", "开始测量", None))
        self.VI_stop.setText(_translate("Dialog", "停止测量", None))
        self.VI_save.setText(_translate("Dialog", "保存数据", None))
        self.groupBox_3.setTitle(_translate("Dialog", "当前状态", None))
        self.label_14.setText(_translate("Dialog", "阀门1", None))
        self.label_13.setText(_translate("Dialog", "阀门2", None))
        self.label_15.setText(_translate("Dialog", "阀门3", None))
        self.label_17.setText(_translate("Dialog", "清洗阀", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

