# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\VI_spectrum\VI_gas_set.ui'
#
# Created: Fri Jan 01 23:26:33 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(480, 320)
        Dialog.setMinimumSize(QtCore.QSize(480, 320))
        Dialog.setMaximumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/gastitle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.const_flow = QtGui.QCheckBox(Dialog)
        self.const_flow.setChecked(False)
        self.const_flow.setObjectName(_fromUtf8("const_flow"))
        self.verticalLayout_3.addWidget(self.const_flow)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(48, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.total_flow = QtGui.QLineEdit(Dialog)
        self.total_flow.setEnabled(False)
        self.total_flow.setMaximumSize(QtCore.QSize(120, 22))
        self.total_flow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.total_flow.setText(_fromUtf8(""))
        self.total_flow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_flow.setObjectName(_fromUtf8("total_flow"))
        self.horizontalLayout_4.addWidget(self.total_flow)
        self.flow_unit = QtGui.QLabel(Dialog)
        self.flow_unit.setObjectName(_fromUtf8("flow_unit"))
        self.horizontalLayout_4.addWidget(self.flow_unit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(40, 22))
        self.label_9.setMaximumSize(QtCore.QSize(40, 22))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(106, 22))
        self.label_8.setMaximumSize(QtCore.QSize(106, 22))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(85, 22))
        self.label_5.setMaximumSize(QtCore.QSize(85, 22))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(86, 22))
        self.label_6.setMaximumSize(QtCore.QSize(86, 22))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.flow1 = QtGui.QCheckBox(Dialog)
        self.flow1.setMinimumSize(QtCore.QSize(79, 20))
        self.flow1.setMaximumSize(QtCore.QSize(79, 20))
        self.flow1.setObjectName(_fromUtf8("flow1"))
        self.horizontalLayout.addWidget(self.flow1)
        self.flow1_range = QtGui.QLineEdit(Dialog)
        self.flow1_range.setEnabled(False)
        self.flow1_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow1_range.setObjectName(_fromUtf8("flow1_range"))
        self.horizontalLayout.addWidget(self.flow1_range)
        self.gas_type1 = QtGui.QComboBox(Dialog)
        self.gas_type1.setMinimumSize(QtCore.QSize(106, 21))
        self.gas_type1.setMaximumSize(QtCore.QSize(106, 21))
        self.gas_type1.setObjectName(_fromUtf8("gas_type1"))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.gas_type1.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.gas_type1)
        self.flow1_ratio = QtGui.QLineEdit(Dialog)
        self.flow1_ratio.setEnabled(False)
        self.flow1_ratio.setObjectName(_fromUtf8("flow1_ratio"))
        self.horizontalLayout.addWidget(self.flow1_ratio)
        self.flow1_rate = QtGui.QLineEdit(Dialog)
        self.flow1_rate.setObjectName(_fromUtf8("flow1_rate"))
        self.horizontalLayout.addWidget(self.flow1_rate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.flow2 = QtGui.QCheckBox(Dialog)
        self.flow2.setMinimumSize(QtCore.QSize(79, 20))
        self.flow2.setMaximumSize(QtCore.QSize(79, 20))
        self.flow2.setObjectName(_fromUtf8("flow2"))
        self.horizontalLayout_2.addWidget(self.flow2)
        self.flow2_range = QtGui.QLineEdit(Dialog)
        self.flow2_range.setEnabled(False)
        self.flow2_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow2_range.setObjectName(_fromUtf8("flow2_range"))
        self.horizontalLayout_2.addWidget(self.flow2_range)
        self.gas_type2 = QtGui.QComboBox(Dialog)
        self.gas_type2.setMinimumSize(QtCore.QSize(106, 21))
        self.gas_type2.setMaximumSize(QtCore.QSize(106, 21))
        self.gas_type2.setObjectName(_fromUtf8("gas_type2"))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.gas_type2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.gas_type2)
        self.flow2_ratio = QtGui.QLineEdit(Dialog)
        self.flow2_ratio.setEnabled(False)
        self.flow2_ratio.setObjectName(_fromUtf8("flow2_ratio"))
        self.horizontalLayout_2.addWidget(self.flow2_ratio)
        self.flow2_rate = QtGui.QLineEdit(Dialog)
        self.flow2_rate.setObjectName(_fromUtf8("flow2_rate"))
        self.horizontalLayout_2.addWidget(self.flow2_rate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.flow3 = QtGui.QCheckBox(Dialog)
        self.flow3.setMinimumSize(QtCore.QSize(79, 20))
        self.flow3.setMaximumSize(QtCore.QSize(79, 20))
        self.flow3.setObjectName(_fromUtf8("flow3"))
        self.horizontalLayout_3.addWidget(self.flow3)
        self.flow3_range = QtGui.QLineEdit(Dialog)
        self.flow3_range.setEnabled(False)
        self.flow3_range.setMaximumSize(QtCore.QSize(40, 18))
        self.flow3_range.setObjectName(_fromUtf8("flow3_range"))
        self.horizontalLayout_3.addWidget(self.flow3_range)
        self.gas_type3 = QtGui.QComboBox(Dialog)
        self.gas_type3.setMinimumSize(QtCore.QSize(106, 21))
        self.gas_type3.setMaximumSize(QtCore.QSize(106, 21))
        self.gas_type3.setObjectName(_fromUtf8("gas_type3"))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.gas_type3.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.gas_type3)
        self.flow3_ratio = QtGui.QLineEdit(Dialog)
        self.flow3_ratio.setEnabled(False)
        self.flow3_ratio.setObjectName(_fromUtf8("flow3_ratio"))
        self.horizontalLayout_3.addWidget(self.flow3_ratio)
        self.flow3_rate = QtGui.QLineEdit(Dialog)
        self.flow3_rate.setObjectName(_fromUtf8("flow3_rate"))
        self.horizontalLayout_3.addWidget(self.flow3_rate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gas_save = QtGui.QPushButton(Dialog)
        self.gas_save.setObjectName(_fromUtf8("gas_save"))
        self.horizontalLayout_6.addWidget(self.gas_save)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gas_cancel = QtGui.QPushButton(Dialog)
        self.gas_cancel.setObjectName(_fromUtf8("gas_cancel"))
        self.horizontalLayout_6.addWidget(self.gas_cancel)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.gas_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "VI谱气压控制", None))
        self.const_flow.setText(_translate("Dialog", "恒定气体总流量", None))
        self.label_4.setText(_translate("Dialog", "总流量", None))
        self.flow_unit.setText(_translate("Dialog", "mL", None))
        self.label_9.setText(_translate("Dialog", "量程", None))
        self.label_8.setText(_translate("Dialog", "气体类型", None))
        self.label_5.setText(_translate("Dialog", "百分比", None))
        self.label_6.setText(_translate("Dialog", "流量", None))
        self.flow1.setText(_translate("Dialog", "流量计1", None))
        self.flow1_range.setText(_translate("Dialog", "2000", None))
        self.gas_type1.setItemText(0, _translate("Dialog", "空气", None))
        self.gas_type1.setItemText(1, _translate("Dialog", "氩气", None))
        self.gas_type1.setItemText(2, _translate("Dialog", "四氟化碳", None))
        self.gas_type1.setItemText(3, _translate("Dialog", "甲烷", None))
        self.gas_type1.setItemText(4, _translate("Dialog", "三氟甲烷", None))
        self.gas_type1.setItemText(5, _translate("Dialog", "乙烯", None))
        self.gas_type1.setItemText(6, _translate("Dialog", "乙烷", None))
        self.gas_type1.setItemText(7, _translate("Dialog", "六氟乙烷", None))
        self.gas_type1.setItemText(8, _translate("Dialog", "丙烯", None))
        self.gas_type1.setItemText(9, _translate("Dialog", "丙烷", None))
        self.gas_type1.setItemText(10, _translate("Dialog", "异丁烯", None))
        self.gas_type1.setItemText(11, _translate("Dialog", "正丁烷", None))
        self.gas_type1.setItemText(12, _translate("Dialog", "异丁烷", None))
        self.gas_type1.setItemText(13, _translate("Dialog", "一氧化碳", None))
        self.gas_type1.setItemText(14, _translate("Dialog", "二氧化碳", None))
        self.gas_type1.setItemText(15, _translate("Dialog", "氯气", None))
        self.gas_type1.setItemText(16, _translate("Dialog", "氢气", None))
        self.gas_type1.setItemText(17, _translate("Dialog", "氯化氢", None))
        self.gas_type1.setItemText(18, _translate("Dialog", "氦气", None))
        self.gas_type1.setItemText(19, _translate("Dialog", "氪气", None))
        self.gas_type1.setItemText(20, _translate("Dialog", "氮气", None))
        self.gas_type1.setItemText(21, _translate("Dialog", "三氟化氮", None))
        self.gas_type1.setItemText(22, _translate("Dialog", "一氧化氮", None))
        self.gas_type1.setItemText(23, _translate("Dialog", "一氧化二氮", None))
        self.gas_type1.setItemText(24, _translate("Dialog", "氖气", None))
        self.gas_type1.setItemText(25, _translate("Dialog", "氧气", None))
        self.gas_type1.setItemText(26, _translate("Dialog", "硅烷", None))
        self.gas_type1.setItemText(27, _translate("Dialog", "六氟化硫", None))
        self.gas_type1.setItemText(28, _translate("Dialog", "二氧化硫", None))
        self.gas_type1.setItemText(29, _translate("Dialog", "氙气", None))
        self.flow2.setText(_translate("Dialog", "流量计2", None))
        self.flow2_range.setText(_translate("Dialog", "500", None))
        self.gas_type2.setItemText(0, _translate("Dialog", "空气", None))
        self.gas_type2.setItemText(1, _translate("Dialog", "氩气", None))
        self.gas_type2.setItemText(2, _translate("Dialog", "四氟化碳", None))
        self.gas_type2.setItemText(3, _translate("Dialog", "甲烷", None))
        self.gas_type2.setItemText(4, _translate("Dialog", "三氟甲烷", None))
        self.gas_type2.setItemText(5, _translate("Dialog", "乙烯", None))
        self.gas_type2.setItemText(6, _translate("Dialog", "乙烷", None))
        self.gas_type2.setItemText(7, _translate("Dialog", "六氟乙烷", None))
        self.gas_type2.setItemText(8, _translate("Dialog", "丙烯", None))
        self.gas_type2.setItemText(9, _translate("Dialog", "丙烷", None))
        self.gas_type2.setItemText(10, _translate("Dialog", "异丁烯", None))
        self.gas_type2.setItemText(11, _translate("Dialog", "正丁烷", None))
        self.gas_type2.setItemText(12, _translate("Dialog", "异丁烷", None))
        self.gas_type2.setItemText(13, _translate("Dialog", "一氧化碳", None))
        self.gas_type2.setItemText(14, _translate("Dialog", "二氧化碳", None))
        self.gas_type2.setItemText(15, _translate("Dialog", "氯气", None))
        self.gas_type2.setItemText(16, _translate("Dialog", "氢气", None))
        self.gas_type2.setItemText(17, _translate("Dialog", "氯化氢", None))
        self.gas_type2.setItemText(18, _translate("Dialog", "氦气", None))
        self.gas_type2.setItemText(19, _translate("Dialog", "氪气", None))
        self.gas_type2.setItemText(20, _translate("Dialog", "氮气", None))
        self.gas_type2.setItemText(21, _translate("Dialog", "三氟化氮", None))
        self.gas_type2.setItemText(22, _translate("Dialog", "一氧化氮", None))
        self.gas_type2.setItemText(23, _translate("Dialog", "一氧化二氮", None))
        self.gas_type2.setItemText(24, _translate("Dialog", "氖气", None))
        self.gas_type2.setItemText(25, _translate("Dialog", "氧气", None))
        self.gas_type2.setItemText(26, _translate("Dialog", "硅烷", None))
        self.gas_type2.setItemText(27, _translate("Dialog", "六氟化硫", None))
        self.gas_type2.setItemText(28, _translate("Dialog", "二氧化硫", None))
        self.gas_type2.setItemText(29, _translate("Dialog", "氙气", None))
        self.flow3.setText(_translate("Dialog", "流量计3", None))
        self.flow3_range.setText(_translate("Dialog", "50", None))
        self.gas_type3.setItemText(0, _translate("Dialog", "空气", None))
        self.gas_type3.setItemText(1, _translate("Dialog", "氩气", None))
        self.gas_type3.setItemText(2, _translate("Dialog", "四氟化碳", None))
        self.gas_type3.setItemText(3, _translate("Dialog", "甲烷", None))
        self.gas_type3.setItemText(4, _translate("Dialog", "三氟甲烷", None))
        self.gas_type3.setItemText(5, _translate("Dialog", "乙烯", None))
        self.gas_type3.setItemText(6, _translate("Dialog", "乙烷", None))
        self.gas_type3.setItemText(7, _translate("Dialog", "六氟乙烷", None))
        self.gas_type3.setItemText(8, _translate("Dialog", "丙烯", None))
        self.gas_type3.setItemText(9, _translate("Dialog", "丙烷", None))
        self.gas_type3.setItemText(10, _translate("Dialog", "异丁烯", None))
        self.gas_type3.setItemText(11, _translate("Dialog", "正丁烷", None))
        self.gas_type3.setItemText(12, _translate("Dialog", "异丁烷", None))
        self.gas_type3.setItemText(13, _translate("Dialog", "一氧化碳", None))
        self.gas_type3.setItemText(14, _translate("Dialog", "二氧化碳", None))
        self.gas_type3.setItemText(15, _translate("Dialog", "氯气", None))
        self.gas_type3.setItemText(16, _translate("Dialog", "氢气", None))
        self.gas_type3.setItemText(17, _translate("Dialog", "氯化氢", None))
        self.gas_type3.setItemText(18, _translate("Dialog", "氦气", None))
        self.gas_type3.setItemText(19, _translate("Dialog", "氪气", None))
        self.gas_type3.setItemText(20, _translate("Dialog", "氮气", None))
        self.gas_type3.setItemText(21, _translate("Dialog", "三氟化氮", None))
        self.gas_type3.setItemText(22, _translate("Dialog", "一氧化氮", None))
        self.gas_type3.setItemText(23, _translate("Dialog", "一氧化二氮", None))
        self.gas_type3.setItemText(24, _translate("Dialog", "氖气", None))
        self.gas_type3.setItemText(25, _translate("Dialog", "氧气", None))
        self.gas_type3.setItemText(26, _translate("Dialog", "硅烷", None))
        self.gas_type3.setItemText(27, _translate("Dialog", "六氟化硫", None))
        self.gas_type3.setItemText(28, _translate("Dialog", "二氧化硫", None))
        self.gas_type3.setItemText(29, _translate("Dialog", "氙气", None))
        self.gas_save.setText(_translate("Dialog", "保存", None))
        self.gas_cancel.setText(_translate("Dialog", "退出", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

