# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\WorkDir\gas-sensing_resistors\ST_spectrum\ST_2400.ui'
#
# Created: Tue Apr 12 22:50:19 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UI_sens2400(object):
    def setupUi(self, UI_sens2400):
        UI_sens2400.setObjectName(_fromUtf8("UI_sens2400"))
        UI_sens2400.resize(486, 360)
        UI_sens2400.setMinimumSize(QtCore.QSize(480, 360))
        UI_sens2400.setMaximumSize(QtCore.QSize(486, 360))
        font = QtGui.QFont()
        font.setPointSize(12)
        UI_sens2400.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/yb.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI_sens2400.setWindowIcon(icon)
        self.verticalLayout_8 = QtGui.QVBoxLayout(UI_sens2400)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(UI_sens2400)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.res_range = QtGui.QComboBox(UI_sens2400)
        self.res_range.setMaximumSize(QtCore.QSize(16777215, 22))
        self.res_range.setObjectName(_fromUtf8("res_range"))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.res_range.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.res_range)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.res_detect = QtGui.QPushButton(UI_sens2400)
        self.res_detect.setMaximumSize(QtCore.QSize(16777215, 22))
        self.res_detect.setObjectName(_fromUtf8("res_detect"))
        self.horizontalLayout_14.addWidget(self.res_detect)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_3 = QtGui.QLabel(UI_sens2400)
        self.label_3.setMaximumSize(QtCore.QSize(32, 22))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.detV = QtGui.QLineEdit(UI_sens2400)
        self.detV.setEnabled(False)
        self.detV.setMinimumSize(QtCore.QSize(60, 22))
        self.detV.setMaximumSize(QtCore.QSize(65535, 22))
        self.detV.setObjectName(_fromUtf8("detV"))
        self.horizontalLayout_9.addWidget(self.detV)
        self.label_7 = QtGui.QLabel(UI_sens2400)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(UI_sens2400)
        self.label_6.setMaximumSize(QtCore.QSize(32, 22))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.detI = QtGui.QLineEdit(UI_sens2400)
        self.detI.setEnabled(False)
        self.detI.setMinimumSize(QtCore.QSize(60, 22))
        self.detI.setMaximumSize(QtCore.QSize(65535, 22))
        self.detI.setText(_fromUtf8(""))
        self.detI.setObjectName(_fromUtf8("detI"))
        self.horizontalLayout_10.addWidget(self.detI)
        self.label_11 = QtGui.QLabel(UI_sens2400)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(UI_sens2400)
        self.label_2.setMaximumSize(QtCore.QSize(32, 22))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.detR = QtGui.QLineEdit(UI_sens2400)
        self.detR.setEnabled(False)
        self.detR.setMinimumSize(QtCore.QSize(60, 22))
        self.detR.setMaximumSize(QtCore.QSize(65535, 22))
        self.detR.setObjectName(_fromUtf8("detR"))
        self.horizontalLayout_11.addWidget(self.detR)
        self.label_12 = QtGui.QLabel(UI_sens2400)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.mode2or4 = QtGui.QComboBox(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mode2or4.setFont(font)
        self.mode2or4.setObjectName(_fromUtf8("mode2or4"))
        self.mode2or4.addItem(_fromUtf8(""))
        self.mode2or4.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.mode2or4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.output_mode = QtGui.QComboBox(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_mode.setFont(font)
        self.output_mode.setObjectName(_fromUtf8("output_mode"))
        self.output_mode.addItem(_fromUtf8(""))
        self.output_mode.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.output_mode)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.IV_mode = QtGui.QRadioButton(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IV_mode.setFont(font)
        self.IV_mode.setChecked(True)
        self.IV_mode.setObjectName(_fromUtf8("IV_mode"))
        self.verticalLayout_6.addWidget(self.IV_mode)
        self.groupBox_2 = QtGui.QGroupBox(UI_sens2400)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(64, 29))
        self.label_4.setMaximumSize(QtCore.QSize(64, 29))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.VI_voltage = QtGui.QLineEdit(self.groupBox_2)
        self.VI_voltage.setMinimumSize(QtCore.QSize(67, 22))
        self.VI_voltage.setMaximumSize(QtCore.QSize(67, 22))
        self.VI_voltage.setObjectName(_fromUtf8("VI_voltage"))
        self.horizontalLayout_4.addWidget(self.VI_voltage)
        self.voltage_unit = QtGui.QComboBox(self.groupBox_2)
        self.voltage_unit.setObjectName(_fromUtf8("voltage_unit"))
        self.voltage_unit.addItem(_fromUtf8(""))
        self.voltage_unit.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.voltage_unit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.VI_current_range = QtGui.QComboBox(self.groupBox_2)
        self.VI_current_range.setObjectName(_fromUtf8("VI_current_range"))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.VI_current_range.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.VI_current_range)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.VI_mode = QtGui.QRadioButton(UI_sens2400)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.VI_mode.setFont(font)
        self.VI_mode.setObjectName(_fromUtf8("VI_mode"))
        self.verticalLayout_5.addWidget(self.VI_mode)
        self.groupBox_3 = QtGui.QGroupBox(UI_sens2400)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(64, 29))
        self.label_5.setMaximumSize(QtCore.QSize(64, 29))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.IV_current = QtGui.QLineEdit(self.groupBox_3)
        self.IV_current.setMinimumSize(QtCore.QSize(67, 22))
        self.IV_current.setMaximumSize(QtCore.QSize(67, 22))
        self.IV_current.setObjectName(_fromUtf8("IV_current"))
        self.horizontalLayout_6.addWidget(self.IV_current)
        self.current_unit = QtGui.QComboBox(self.groupBox_3)
        self.current_unit.setObjectName(_fromUtf8("current_unit"))
        self.current_unit.addItem(_fromUtf8(""))
        self.current_unit.addItem(_fromUtf8(""))
        self.current_unit.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.current_unit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_15.addWidget(self.label_10)
        self.IV_voltage_range = QtGui.QComboBox(self.groupBox_3)
        self.IV_voltage_range.setObjectName(_fromUtf8("IV_voltage_range"))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.IV_voltage_range.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.IV_voltage_range)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.ST2400_save = QtGui.QPushButton(UI_sens2400)
        self.ST2400_save.setObjectName(_fromUtf8("ST2400_save"))
        self.horizontalLayout_8.addWidget(self.ST2400_save)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.ST2400_exit = QtGui.QPushButton(UI_sens2400)
        self.ST2400_exit.setObjectName(_fromUtf8("ST2400_exit"))
        self.horizontalLayout_8.addWidget(self.ST2400_exit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)

        self.retranslateUi(UI_sens2400)
        QtCore.QObject.connect(self.ST2400_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), UI_sens2400.close)
        QtCore.QMetaObject.connectSlotsByName(UI_sens2400)

    def retranslateUi(self, UI_sens2400):
        UI_sens2400.setWindowTitle(_translate("UI_sens2400", "灵敏度-温度谱仪器设置", None))
        self.label_13.setText(_translate("UI_sens2400", "电阻范围", None))
        self.res_range.setItemText(0, _translate("UI_sens2400", "100", None))
        self.res_range.setItemText(1, _translate("UI_sens2400", "1K", None))
        self.res_range.setItemText(2, _translate("UI_sens2400", "10K", None))
        self.res_range.setItemText(3, _translate("UI_sens2400", "100K", None))
        self.res_range.setItemText(4, _translate("UI_sens2400", "1M", None))
        self.res_range.setItemText(5, _translate("UI_sens2400", "10M", None))
        self.res_range.setItemText(6, _translate("UI_sens2400", "100M", None))
        self.res_range.setItemText(7, _translate("UI_sens2400", "200M", None))
        self.res_detect.setText(_translate("UI_sens2400", "电阻探测", None))
        self.label_3.setText(_translate("UI_sens2400", "电压", None))
        self.label_7.setText(_translate("UI_sens2400", "V", None))
        self.label_6.setText(_translate("UI_sens2400", "电流", None))
        self.label_11.setText(_translate("UI_sens2400", "A", None))
        self.label_2.setText(_translate("UI_sens2400", "电阻", None))
        self.label_12.setText(_translate("UI_sens2400", "Ω", None))
        self.label.setText(_translate("UI_sens2400", "测量模式", None))
        self.mode2or4.setItemText(0, _translate("UI_sens2400", "两线制", None))
        self.mode2or4.setItemText(1, _translate("UI_sens2400", "四线制", None))
        self.label_8.setText(_translate("UI_sens2400", "输出模式", None))
        self.output_mode.setItemText(0, _translate("UI_sens2400", "脉冲输出", None))
        self.output_mode.setItemText(1, _translate("UI_sens2400", "连续输出", None))
        self.IV_mode.setText(_translate("UI_sens2400", "通电压，测电流", None))
        self.groupBox_2.setTitle(_translate("UI_sens2400", "I-V模式设置", None))
        self.label_4.setText(_translate("UI_sens2400", "激励电压", None))
        self.voltage_unit.setItemText(0, _translate("UI_sens2400", "mV", None))
        self.voltage_unit.setItemText(1, _translate("UI_sens2400", "V", None))
        self.label_9.setText(_translate("UI_sens2400", "电流量程", None))
        self.VI_current_range.setItemText(0, _translate("UI_sens2400", "AUTO", None))
        self.VI_current_range.setItemText(1, _translate("UI_sens2400", "10pA", None))
        self.VI_current_range.setItemText(2, _translate("UI_sens2400", "100pA", None))
        self.VI_current_range.setItemText(3, _translate("UI_sens2400", "1uA", None))
        self.VI_current_range.setItemText(4, _translate("UI_sens2400", "10uA", None))
        self.VI_current_range.setItemText(5, _translate("UI_sens2400", "100uA", None))
        self.VI_current_range.setItemText(6, _translate("UI_sens2400", "1mA", None))
        self.VI_current_range.setItemText(7, _translate("UI_sens2400", "10mA", None))
        self.VI_current_range.setItemText(8, _translate("UI_sens2400", "100mA", None))
        self.VI_current_range.setItemText(9, _translate("UI_sens2400", "1A", None))
        self.VI_mode.setText(_translate("UI_sens2400", "通电流，测电压", None))
        self.groupBox_3.setTitle(_translate("UI_sens2400", "V-I模式设置", None))
        self.label_5.setText(_translate("UI_sens2400", "激励电流", None))
        self.current_unit.setItemText(0, _translate("UI_sens2400", "uA", None))
        self.current_unit.setItemText(1, _translate("UI_sens2400", "mA", None))
        self.current_unit.setItemText(2, _translate("UI_sens2400", "A", None))
        self.label_10.setText(_translate("UI_sens2400", "电压量程", None))
        self.IV_voltage_range.setItemText(0, _translate("UI_sens2400", "AUTO", None))
        self.IV_voltage_range.setItemText(1, _translate("UI_sens2400", "1uV", None))
        self.IV_voltage_range.setItemText(2, _translate("UI_sens2400", "10uV", None))
        self.IV_voltage_range.setItemText(3, _translate("UI_sens2400", "100uV", None))
        self.IV_voltage_range.setItemText(4, _translate("UI_sens2400", "1mV", None))
        self.IV_voltage_range.setItemText(5, _translate("UI_sens2400", "10mV", None))
        self.IV_voltage_range.setItemText(6, _translate("UI_sens2400", "100mV", None))
        self.IV_voltage_range.setItemText(7, _translate("UI_sens2400", "1V", None))
        self.IV_voltage_range.setItemText(8, _translate("UI_sens2400", "10V", None))
        self.IV_voltage_range.setItemText(9, _translate("UI_sens2400", "210V", None))
        self.ST2400_save.setText(_translate("UI_sens2400", "保存", None))
        self.ST2400_exit.setText(_translate("UI_sens2400", "退出", None))

import mypic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UI_sens2400 = QtGui.QDialog()
    ui = Ui_UI_sens2400()
    ui.setupUi(UI_sens2400)
    UI_sens2400.show()
    sys.exit(app.exec_())

